/* en/content.js
 * ENGLISH LANGUAGE CONTENT for ingo-steinke.com
 */
module.exports = {
  /* meta data */
  "language": "en",
  "canonicalHref": "https://www.ingo-steinke.com/",
  "canonicalHrefNoTrailingSlash": "https://www.ingo-steinke.com",
  "shortHref": "www.ingo-steinke.com",
  "alternateHreflang": "de",
  "alternateHref": "https://www.ingo-steinke.de/",
  "metaAuthor": "Ingo Steinke",
  "pageTitle": "Ingo Steinke, Sustainable and Creative Web Developer in Berlin",
  "pageDescription": "Ingo Steinke is a creative web developer focused on sustainable web development with more than 20 years of professional experience.",
  "pageDescription-en": "Ingo Steinke is a creative web developer focused on sustainable web development with more than 20 years of professional experience..",
  "pDomainVerify": "4c4296e5835f4a47eb2c2e5488a99d71",
  "googleSiteVerification": "rKw6ukUkdoGGTo5dFb1sv4HQXN5wy6GysuVCRkt1FTg",
  "notFoundTitle": "Ingo Steinke - page not found",
  "notFoundHeading": "Sorry, we couldn't find that page.",
  "notFoundDescription": "The document you are looking for does not exist at this web address. You can find more content on my",
  "notFoundHomepageLinkUrl" : "https://www.ingo-steinke.com/",
  "notFoundHomepageLinkText" : "home page",
  /* header */
  "jumbotronImageAlt": "Portrait of web developer Ingo Steinke in Berlin",
  "jumbotronHeader": "Ingo Steinke",
  "jumbotronTagline": "Creative Web Developer",
  "linkToTop": "to top",
  "menuLabel": "table of contents",
  "menuOpen": "open menu",
  "menuClose": "close menu",
  "menuButton": "contents",
  "targetProjects": "projects",
  "targetServices": "services",
  "targetSkills": "skills",
  "targetAboutMe": "about me",
  "targetTalksEvents": "talks",
  "targetContact": "contact",
  "targetImprint": "imprint",
  "targetPrivacy": "privacy",
  "targetOtherLanguage": "deutsch",
  "targetOtherLanguageTitle": "zur deutschen Sprache wechseln",
  /* page content */
  "introHeading": "Your Internet Presence Can Inspire Your Customers",
  "intro": "My name is Ingo Steinke. I'm a sustainable and creative web developer with more than 20 years of professional experience. Customers who have benefited from my work include",
  "spacedAnd": ", and",
  "andA": "and a",
  "currentlyEcologicalIam": "I enjoy working for customers with an ecological and ethical focus in their work! I'm a",
  "memberOf": "a member of",
  "careAboutGoingBeyond": "Creativity, flexibility, and thoughtfulness are the main values that guide my work and personal lives. I am deeply interested in how sustainability, culture, and art come together, and I strive to bring what I learn into my work every day.",
  "workWithMeHeading": "Let's Work Together!",
  "workWithMe":"Do you want to overhaul your website? Does your team need support from a front-end developer with full-stack experience?",
  "ctaContact": "Call me or leave a message!",
  "workWithMe2": "I'm happy to discuss your project with no obligations over a coffee in Berlin, via Zoom, or in a phone call.",
  "projectsHeading": "Web and Software Projects",
  "projects": "This is a selection of my past projects. Take a look and see what you think!",
  "projectsScreenshots": "Screenshots",
  "projectPortfolioRelaunchHeading": "Portfolio Relaunch",
  "projectPortfolioRelaunch1": "My relaunched portfolio at",
  "projectPortfolioRelaunch2": "Ingo-Steinke.com",
  "projectPortfolioRelaunch3": "reflects my work as a web developer. Minimalist design, modern typography, cutting-edge technology, and extensive textual revisions characterise my updated professional portfolio. Source Code:",
  "projectPortfolioRelaunchHashtag1": "HTML 5",
  "projectPortfolioRelaunchHashtag2": "CSS 3",
  "projectPortfolioRelaunchHashtag3": "JavaScript",
  "projectPortfolioRelaunchHashtag4": "Liquid",
  "projectPortfolioRelaunchHashtag5": "Eleventy",
  "projectAtomicRelaunchHeading": "Atomic Design System",
  "projectAtomicRelaunch1": "As senior lead developer on a team of front-end web developers, I developed a modular system for the relaunch of an international corporate customer's multiple websites.",
  "projectAtomicRelaunch2": "The",
  "projectAtomicRelaunch3": "Fractal",
  "projectAtomicRelaunch4": " framework served as a technical basis.",
  "projectAtomicRelaunchHashtag1": "HTML",
  "projectAtomicRelaunchHashtag2": "CSS",
  "projectAtomicRelaunchHashtag3": "Fractal",
  "projectAtomicRelaunchHashtag4": "Handlebars",
  "projectAtomicRelaunchHashtag5": "Webpack",
  "projectPhotographyHeading": "WordPress Optimization",
  "projectPhotography1": "I extended the content and improved loading speed, accessibility, and mobile display of various WordPress websites like",
  "projectPhotography2": "Malte-Reiter.de",
  "projectPhotography3Spaced": ", a sustainable photographer's portfolio including gallery pages with a lot of existing images",
  "projectPhotographyHashtag1": "WordPress",
  "projectPhotographyHashtag2": "BrowserStack",
  "projectPhotographyHashtag3": "PageSpeed",
  "projectPhotographyHashtag4": "CSS",
  "projectWandelpunktHeading": "Optimization and Enhancement",
  "projectWandelpunkt1": "For the Sustainable Development Goals (SDG) consultants at",
  "projectWandelpunkt2": "Wandelpunkt-Consulting.de",
  "projectWandelpunkt3Spaced": ", I added new content and optimised the blog's loading speed and accessibility.",
  "projectWandelpunktHashtag1": "WordPress",
  "projectWandelpunktHashtag2": "Semplice",
  "projectWandelpunktHashtag3": "CSS",
  "projectWandelpunktHashtag4": "SVG",
  "projectWordpressWooHeading": "WooCommerce-Shop",
  "projectWordpressWoo1": "I support the farm food shop",
  "projectWordpressWoo2": "by enhancing the full site editing block theme for their WooCommerce shop",
  "projectWordpressWooHashtag1": "WordPress",
  "projectWordpressWooHashtag2": "WooCommerce",
  "projectWordpressWooHashtag3": "PHP",
  "projectWordpressWooHashtag4": "CSS",
  "projectShopwareCostPluginHeading": "Plugin for Shopware",
  "projectShopwareCostPluginLinkUrl": "https://store.shopware.com/en/ingos57544164693f/cost-transparency.html",
  "projectShopwareCostPlugin1": "Sustainability in e-commerce also includes price transparency. My free plugin",
  "projectShopwareCostPlugin2": "&quot;Cost Transparency&quot;",
  "projectShopwareCostPlugin3": "extends the product details in Shopware 6, adding an interactive graphic that illustrates different shares of the total price.",
  "projectShopwareCostPluginHashtag1": "Shopware 6",
  "projectShopwareCostPluginHashtag2": "PHP",
  "projectShopwareCostPluginHashtag3": "Twig",
  "projectShopwareCostPluginHashtag4": "CSS",
  "projectShopwareCostPluginHashtag5": "JavaScript",
  "projectShopwarePluginHeading": "Plugin for Shopware",
  "projectShopwarePlugin1": "My first Shopware 6 project was an administrative plugin that facilitates load time optimisation for online shops via an API. It was released",
  "projectShopwarePlugin2": "at the official Shopware store",
  "projectShopwarePlugin3": "in 2020.",
  "projectShopwarePluginHashtag1": "Shopware 6",
  "projectShopwarePluginHashtag2": "Symfony",
  "projectShopwarePluginHashtag3": "PHP",
  "projectShopwarePluginHashtag4": "Vue.js",
  "projectReactAppHeading": "React Web App",
  "projectReactApp1": "wao.io's graphical user interface visualised technical data and allowed webmasters to configure how their websites are optimised. I developed and updated app components",
  "projectReactApp2": "as a member of the front-end and support team",
  "projectReactApp3": "",
  "projectReactAppHashtag1": "React",
  "projectReactAppHashtag2": "JSX",
  "projectReactAppHashtag3": "ES6",
  "projectReactAppHashtag4": "CSS-in-JS",
  "projectReactAppHashtag5": "Storybook",
  "projectWebperfTalkHeading": "Performance Talk",
  "projectWebperfTalk1": "How to speed up my website?",
  "projectWebperfTalk2": "At the Cologne Web Performance Meetup",
  "projectWebperfTalk3": ", Angelina Farsch and me explained how website owners can analyze and optimise their site speed without changing the code.",
  "projectWebperfTalkHashtag1": "Meetup",
  "projectWebperfTalkHashtag2": "Talk",
  "projectWebperfTalkHashtag3": "Jitsi",
  "projectKleiderordnungHeading": "Sustainable Fashion Website",
  "projectKleiderordnung1": "",
  "projectKleiderordnung2": "Kleiderordnung.Berlin",
  "projectKleiderordnung3": "is sustainable stylist Tina Steinke's WordPress-based website, featuring an individual front page based on a graphic design by Ina Nixdorf.",
  "projectKleiderordnungCode": "Source code:",
  "projectKleiderordnungHashtag1": "HTML",
  "projectKleiderordnungHashtag2": "CSS",
  "projectKleiderordnungHashtag3": "JavaScript",
  "projectKleiderordnungHashtag4": "PHP",
  "projectKleiderordnungHashtag5": "WordPress",
  "projectDaskannstdutunHeading": "Climate Psychology Campaign",
  "projectDaskannstdutun1": "A collaboration between ",
  "projectDaskannstdutunAnd": "and",
  "projectDaskannstdutunCreatedSpaced": ", the voluntary impact campaign",
  "projectDaskannstdutunDKDT": "&quot;You can do it&quot; (&quot;Das kannst du tun&quot;)",
  "projectDaskannstdutunLast": "supports mental health and ecological action. I optimised the responsive display.",
  "projectDaskannstdutunHashtag1": "WordPress",
  "projectDaskannstdutunHashtag2": "Elementor",
  "projectDaskannstdutunHashtag3": "CSS",
  "projectPlantedHeading" : "Frontend Enhancement",
  "projectPlanted1": "After doing a",
  "projectPlanted2": "ClimateHack",
  "projectPlanted3": "project together in 2021, I supported the Cologne based startup",
  "projectPlanted4": "Planted",
  "projectPlanted5": "by enhancing a webflow project, integrating payment providers, and onboarding a new developer.",
  "projectPlantedHashtag1": "Webflow",
  "projectPlantedHashtag2": "JavaScript",
  "projectPlantedHashtag3": "HTML",
  "projectPlantedHashtag4": "CSS",
  /* work */
  "workHeading": "Long-Lasting Solutions",
  "work": "I can implement your layouts across platforms in a responsive and accessible way. My goal is to build long-lasting solutions that are elegant, transparent, and easy to maintain. Modular components, themes, as well as CSS frameworks and methodologies like BEM and Atomic Design help to simplify collaboration and further development. Continuous testing allows me to discover and eliminate errors at an early stage.",
  "workReliableHeading": "Reliable and Easy to Understand",
  "workReliable": "For me, it's important to explain technological facts in simple words, to understand my customers' requirements, and to look ahead and implement sustainable solutions.",
  "workClientsBenefit": "You benefit from lower maintenance costs, optimised performance, and improved customer contact.",
  "pricingHeading": "Pricing",
  "pricing": "You can choose a time-based fee, or we can agree on a fixed price rate before starting work. My hourly rates depend on the type and extent of the work required, starting at <span class=price>€ 85,- (plus VAT)</span>. Nonprofit organisations and sustainability-oriented startups can request reduced rates. I usually provide an estimate before starting time-based tasks.",
  "workFullstack": "When enhancing existing code, I benefit from professional experience and a pragmatic approach. With back-end and DevOps experience and a high willingness to learn, I can take charge or find a suitable partner for all web development tasks.",
  "workOwnFocus": "My focus is CSS based frontend development.",
  "workCertifiedHeading": "Certified and Transparent",
  "workCertifiedIam": "I am a",
  "workCertifiedSWDev": "certified Shopware 6 Developer",
  "workCertifiedSWDevPartnerPageUrl": "https://store.shopware.com/en/ingo-steinke.html",
  "workCertifiedPdfUrl": "Shopware-6-Certified-Developer-Ingo-Steinke.pdf",
  "workCertifiedAnd": "and a",
  "workCertifiedExtensionPartner": "Shopware Extension Partner",
  "workCertifiedSustainableSourceCodeLinkText": "The source code of my work",
  "workCertifiedSustainable2": "is openly accessible, if data protection allows it. ",
  "workCertifiedSustainableFootprintLinkText": "My website's &quot;CO<sub>2</sub>-footprint&quot;",
  "workCertifiedSustainable3": "is also publicly visible.",
  "workTeamHeading": "Teamwork and Network",
  "workTeam": "I don't have a permanent team but I have established a network of competent business friends, some of whom I have been working with for many years. As a customer, you can also introduce me to the service providers you trust. This way, you retain full control and save yourself the additional work and changing contact partners of traditional agencies.",
  "workPluginsHeading": "Open Source / Plugin Development",
  "workPlugins1": "My preferred approach is to implement back-end interfaces as independent open source modules.",
  "workPlugins5": "I am currently working on WordPress plugins",
  "workPlugins6": "to detect plugin conflicts",
  "workPluginsAnd": "and",
  "workPlugins7": "to send spam reports for WordPress contact forms",
  "workPluginsOther": "I also developed extensions and themes for Shopware, WebStorm, and IntelliJ IDEA, including the free",
  /* Skills */
  "SkillsHeading": "Professional Skills",
  "SkillsWebdevHeading": "Web Development",
  "SkillsWebdevDb": "Database",
  "SkillsLib": "Software Stacks",
  "SkillsLibStaticSiteGenerators": "SSG",
  "SkillsLibDesignSystems": "Design Systems",
  "SkillsOther": "Other Tools",
  "SkillsOtherQa": "Quality Assurance, Tests, and Audits",
  "SkillsOtherVcs": "Source Control, Versioning",
  "SkillsOtherLinter": "Linters, Bundlers, Transpilers",
  "SkillsOtherDevops": "DevOps, Automation",
  "SkillsDevuxImg": "Collaboration, Project Management",
  "SkillsOtherImg": "Image Editing, Image Optimization",
  /* About me, talks, and events */
  "aboutMeHeading": "Work and Passion",
  "aboutMeIntroHeading": "What Still Fascinates Me",
  "aboutMeIntro": "Worldwide communication and inspiration: The World Wide Web connects people using robust and decentralized technology. Websites designed to offer everyone access to this network need to be attractive, fast, and accessible. My work helps to make this dream a reality.",
  "aboutMeCvHeading": "Professional Background",
  "aboutMeCv1": "I co-founded a start-up in 2000 whose first products were interactive websites and browser games. Later, our core business transitioned to search engine optimization and our Active-Webshop software.",
  "aboutMeCv2": "While employed as an e-commerce engineer at Xsite in Düsseldorf from 2010 to 2014, I developed online shops for Shop-Apotheke.com, Ars mundi, and other customers. As a technical consultant at Sevenval Technologies (later Avenga Germany) in Cologne and Berlin, I optimized the loading time and mobile phone compatibility of apps and websites for Frankfurter Allgemeine Zeitung and online shops for Otto Group and created front-end applications for wao.io and other customers. As a freelance web developer since 2020, I have been working for nexum, FoodTogether and Planted.",
  "aboutMeEthicalHeading": "Future Topics and Sustainable Development",
  "aboutMeEthical": "In the IT industry, innovation, transformation, and  digitalization often mean nothing but technological progress. In many cases, social challenges in ecology, equality, participation, safety, and data protection do not receive the priority they deserve. I want to support ethical and ecological projects, for example the transition in the transport sector, renewable energies, environmentally-friendly fashion.",
  "aboutMeEthicalImA": "I'm a",
  "aboutMeEthicalA": "a",
  "aboutMeEthicalandASignatory": ", and I signed the",
  "aboutMeAtDev": "In my",
  "aboutMeDevBlog": "DEV Blog",
  "aboutMeAndOn": "and on",
  "aboutMeOMCLinkText": "open-mind-culture.org",
  "aboutMeIRegularly": "I regularly publish articles about web development and related technological and societal topics.",
  "talksHeading": "Talks, Events, and Customer Feedback",
  "talksImageAlt": "Photograph: Ingo Steinke, Frontend Web Developer, Freelancer, on never code alone TV in 2021 (partial captions in German)",
  "talksImageCaption": "Image",
  "talksImageLinkText": "Never Code Alone Conference 2021",
  "talks": "At conferences, courses, and meetups I like to exchange ideas on a professional and personal level.",
  "talks2": "A selection of my past talks:",
  "talkMeetupWebVitals": "Core Web Vitals: Web Performance and Usability",
  "talkMeetupWebVitals2": "",
  "talkPerformanceNoCode": "Performance Optimization without Changing Code",
  "talkPerformanceNoCode2": "",
  "talkHsts": "HSTS: Increasing Security without Losing Performance",
  "talkHsts2": "",
  "talkInfrastructure": "Infrastructure for Improved Web Performance",
  "talkInfrastructure2": " (German)",
  "testimonials": "What customers say",
  "testimonialsReadMoreText1": "Read more Google Business testimonials",
  "testimonialsReadMoreLinkUrl1": "https://www.google.com/maps/place/Ingo+Steinke/@54.5871961,-51.7559002,3z/data=!4m13!1m3!11m2!2s1A_qFX3OC2-87_jFnYtJquSLGNds!3e1!3m8!1s0x47b8cf81dc94e4ab:0x756104e1aec1a165!8m2!3d52.4789132!4d13.4417945!9m1!1b1!15sCgEqWgMiASqSARB3ZWJzaXRlX2Rlc2lnbmVy4AEA!16s%2Fg%2F11qsm5r_br",
  "testimonialsReadMoreLinkUrl2": "https://www.provenexpert.com/ingo-steinke-creative-web-developer/",
  "testimonialDanielaQuote": "I had the pleasure of working with Ingo and am impressed by his expertise in web development. He is not only technically skilled, but also conceptually strong. I find it particularly impressive that Ingo can come up with a solution for every problem. Last but not least, he is characterized by his strong commitment to sustainability. I can therefore highly recommend him!",
  "testimonialDanielaAuthor": "Daniela, designer",
  "testimonialMalteQuote": "A few programmers and IT people have already worked at my side, but it's only now that I realize what a huge difference it can make.",
  "testimonialMalteAuthor": "Malte, photographer",
  "testimonialPatriciaQuote": "We are totally satisfied with Ingo. Absolutely reliable and great results. 100% recommendation!",
  "testimonialPatriciaAuthor": "Patricia, systemic coach",
  "testimonialsFiveStarRating": "five-star rating",
  /* Interested CTA */
  "interestedHeading": "Interested?",
  "interested": "Contact me to schedule a non-binding appointment! I will reply in a timely manner! You can reach my by phone, email, Signal, or WhatsApp. If I can't take a call, feel free to leave me a voice message!",
  /* Imprint, Contact */
  "imprintHeader": "Imprint and Contact Information",
  "imprintName": "Ingo Steinke",
  "imprintRole": "Web Developer",
  "imprintStreetAddress": "Donaustr. 83 II",
  "imprintPostalCode": "12043",
  "imprintCity": "Berlin",
  "imprintCountryName": "Germany",
  "postalAddressLabel": "Postal address",
  "untilDec22": "until 12/31/2022",
  "contactTel": "+491634684080",
  "contactTelChunks": [
    "+49",
    "163",
    "46",
    "84",
    "08",
    "0"
  ],
  "contactOr": "or",
  "scheduleAMeeting": "schedule a meeting via cal.com",
  "contactFormTitle": "Write me a message:",
  "contactFormMessageSending": "Sending your message...",
  "contactFormMessageSent": "Thanks! Your message has been sent.",
  "contactFormMessageError": "Your message could not be sent!",
  "contactFormLabelName": "name",
  "contactFormPlaceholderYourName": "your name",
  "contactFormLabelEmail": "email",
  "contactFormLabelPhone": "phone",
  "contactFormLabelContact": "contact",
  "contactFormLabelEmailOrPhone": "your phone or email",
  "contactFormLabelMessage": "message",
  "contactFormLabelHomepage": "homepage",
  "contactFormLabelCaptcha": "security question",
  "contactFormButtonSubmit": "send",
  "contactFormButtonSubmitRetry": "send again",
  "contactTelOfflineLabel": "Phone temporarily unavailable",
  "contactInterimLabel": "use interim number instead",
  "contactEmail": "contact@ingo-steinke.com",
  "taxNo": "Tax No.",
  "vatIdLabel": "VAT ID",
  "vatIdNumber": "DE337676808",
  "insurance": "professional liability insurance: Media-Haftfplicht",
  "insuranceTitle": "Professional liability insurance: exali Media-Haftpflicht",
  "bankaccountLabel": "Bank account: GLS Gemeinschaftsbank eG",
  "bankaccountNumberChunks": [
    "DE89",
    "4306",
    "0967",
    "3029",
    "8400",
    "00"
  ],
  "profile": "profile",
  "at": "at",
  "vcardQrTitle": "save Ingo Steinke to contacts",
  "vcardQrImgAlt": "QR code: contact Ingo Steinke",
  "vcardQrImgFilename": "ingo-steinke-en-vcard-qr.svg",
  "scanContact": "scan contact",
  "scanAndSaveContact1": "scan to save",
  "scanAndSaveContact2": "contact data",
  "privacyGdpr": "This privacy notice is based on the rules set by the German Federal Data Protection Act (BDSG) and the European General Data Protection Regulation (GDPR). The",
  "privacyGdprImprint": "imprint",
  "privacyGdpr2": "informs how to contact the responsible content provider.",
  "privacyYourRightsHeading": "Your legal rights: access, rectification, erasure, objection",
  "privacyYourRights": "You have the right to object to the processing of your personal data, the right to request copies of your personal data, and the right to request that we erase or rectify your personal data, unless this data is necessary for complying with a statutory retention obligation.",
  "privacyPersonalDataHeading": "What data is collected and processed?",
  "privacyPersonalData": "Personal identification information will only be collected, as far as this is necessary for accounting, customer services and fulfilment of a contract. Personal data will not be processed prior to the users' consent, unless this is impossible for legal reasons or reasons of technological impracticability.",
  "privacyLawHeading": "Legal basis for processing personal data",
  "privacyLaw": "Processing of personal data for fulfilment of a contract is based on article 6(1)(b) of the GDPR.",
  "privacyLaw2": "Processing of personal data to comply with legal obligations is based on article 6(1)(c) of the GDPR.",
  "privacyMinimalHeading": "Data economy and data minimization",
  "privacyMinimal": "Personal data will only be stored as long as necessary in compliance to statutory storage periods. Once this time period has expired, the data will be blocked or erased accordingly.",
  "privacyNoCookies": "This website does not use any cookies, and there are no tracking or advertising services provided by third parties like Google Analytics, Facebook, Meta, or similar service providers.",
  "privacyLinkDisclaimer": "Links to social and professional networks are implemented as links to external websites. Displaying these links in the browser will not cause any data transfer to third parties.",
  "privacyLogfilesHeading": "Website provision and analysis of technical data (logfiles)",
  "privacyLogfiles": "Accessing this website will result in logging data that is necessary for the technical provision of this service: the website address, date and time, amount of transferred data, web browser version, IP address, and possible referrers from other websites linking to the current website. This data will not be stored together with personal data. This data will not be processed for marketing purposes.",
  "privacyLogfilesLaw": "Processing and temporary storage of this kind of data is based on article 6(1)(f) of the GDPR. Apart from providing technological functionality, this data might be used to prevent and prosecute illegal use of this service.",
  "privacyChangesHeading": "Changes to the privacy policy",
  "privacyChanges": "My privacy policy is kept under regular review. Updates will be placed on this place and will become valid on the next visit of this website.",
  "ecofriendlyGreenWebCheckUrl": "https://www.thegreenwebfoundation.org/green-web-check/?url=https%3A%2F%2Fwww.ingo-steinke.com",
  "ecofriendlyGreenWebCheckImageFilename": "badge-greencheckimage-www.ingo-steinke.com-2023",
  "ecofriendlyGreenWebCheckImageOriginalSrc": "https://api.thegreenwebfoundation.org/greencheckimage/www.ingo-steinke.com?nocache=true",
  "ecofriendlyGreenWebCheckImageAlt": "This website is hosted Green by goneo Internet GmbH - checked by thegreenwebfoundation.org",
  "ecofriendlyEcograderUrl": "https://ecograder.com/report/iGbeV7xuZ9hNRVcZNey5hfYT",
  "ecofriendlyEcograderTitle": "In October 2023, this page scored better than 86% of all URLs crawled by Ecograder.",
  "ecofriendlyEcograderScore": "Ecograder Score: 94/100 (0.08 g CO₂e)",
  "listedAt": "Listed at",
  "buttonStopAnimation": "hide animation",
  "buttonStartAnimation": "show animation",
  "buttonToggleAnimation": "animation on/off",
  "updatedWithColon": "updated:",
  "dotIfGerman": "",
  "toggleHighContrast": "toggle high contrast",
  "reduceContrast": "reduce contrast",
  "increaseContrast": "increase contrast",
  "services": "Services",
  "servicesBuildTitle": "Let's build your website!",
  "servicesBuildTitleAlternative": "Website Development",
  "servicesBuild1": "achieve initial success quickly",
  "servicesBuild2": "sustainable concept from the start",
  "servicesBuild3": "long-term collaboration",
  "servicesBuild4": "cooperation with experienced partners",
  "servicesBuildMoreLinkText": "start now",
  "servicesBuildMoreLinkTitle": "Professional Website Creation",
  "servicesBuildMoreSubFooterLinkTitle": "create/build a new website",
  "servicesBuildMoreSubFooterLinkText": "develop",
  "servicesBuildMoreLinkPath": "services/web-development.html",
  "servicesVerifyTitle": "Let's verify your website!",
  "servicesVerifyTitleAlternative": "Website Check",
  "servicesVerify1": "measure your carbon footprint",
  "servicesVerify2": "inspect loading time and accessibility",
  "servicesVerify3": "identify critical errors and problems",
  "servicesVerify4": "pass audits, obtain certifications",
  "servicesVerifyMoreLinkText": "check now",
  "servicesVerifyMoreLinkTitle": "more about audits and analysis",
  "servicesVerifyMoreSubFooterLinkTitle": "check your website's quality",
  "servicesVerifyMoreSubFooterLinkText": "web check",
  "servicesVerifyMoreLinkPath": "services/website-check.html",
  "servicesImproveTitle": "Let's optimize your website!",
  "servicesImproveTitleAlternative": "Website Optimization",
  "servicesImprove1": "your customers will love it",
  "servicesImprove2": "make it work smoothly on every device",
  "servicesImprove3": "make it easy to find on Ecosia and Google",
  "servicesImprove4": "improve and certify its ecological efficiency",
  "servicesImproveMoreLinkText": "optimize now",
  "servicesImproveMoreLinkTitle": "optimization and certification options",
  "servicesImproveMoreSubFooterLinkTitle": "improve existing websites",
  "servicesImproveMoreSubFooterLinkText": "optimize",
  "servicesImproveMoreLinkPath": "services/optimization.html",
  "showLandingpageLinks": "true",
  "landingLinkTitleWordPress":"WordPress website optimized sustainably",
  "landingLinkTextWordPress": "WordPress",
  "landingLinkUrlWordPress": "https://www.ingo-steinke.de/wordpress-website-nachhaltig-optimieren-lassen/",
  "landingLinkTitleShopware": "certified Shopware 6 + frontend web developer",
  "landingLinkTextShopware": "Shopware",
  "landingLinkUrlShopware": "https://www.ingo-steinke.de/zertifizierter-shopware-6-frontend-webentwickler/",
  "landingLinkTitleSustainability": "accessible and climate-friendly website optimization",
  "landingLinkTextSustainability": "sustainability",
  "landingLinkUrlSustainability": "https://www.ingo-steinke.com/services/accessible-climate-website-optimization.html",
  "landingLinkTitleFreelanceBerlin": "freelance web developer in Berlin",
  "landingLinkTextFreelanceBerlin": "freelancer Berlin",
  "landingLinkUrlFreelanceBerlin": "https://www.ingo-steinke.com/services/freelance-webdeveloper-berlin.html"
};
