/* de/content.js
 * GERMAN LANGUAGE CONTENT for ingo-steinke.de
 */
module.exports = {
  /* meta data */
  "language": "de",
  "canonicalHref": "https://www.ingo-steinke.de/",
  "shortHref": "www.ingo-steinke.de",
  "alternateHreflang": "en",
  "alternateHref": "https://www.ingo-steinke.com/",
  "metaAuthor": "Ingo Steinke",
  "pageTitle": "Ingo Steinke, nachhaltiger und kreativer Webentwickler",
  "pageDescription": "Ingo Steinke ist ein kreativer Webentwickler mit Schwerpunkt Frontend und Nachhaltigkeit, mit über 20 Jahren Beruferfahrung.",
  "pageDescription-en": "Ingo Steinke ist ein kreativer Webentwickler mit Schwerpunkt Frontend und Nachhaltigkeit, mit über 20 Jahren Beruferfahrung.",
  "pDomainVerify": "4c4296e5835f4a47eb2c2e5488a99d71",
  "googleSiteVerification": "Qs1p7JgqPLOGD3BYCMGe9EbyNJJEswyala44hnkO6d4",
  /* page content */
  "jumbotronImageAlt": "Portrait of Ingo Steinke",
  "jumbotronHeader": "Ingo Steinke",
  "jumbotronTagline": "Creative Web Developer",
  "linkToTop": "Zum Seitenanfang",
  "menuLabel": "Inhaltsverzeichnis",
  "menuOpen": "Inhaltsverzeichnis öffnen",
  "menuClose": "Inhaltsverzeichnis schließen",
  "menuButton": "Inhalt",
  "targetProjects": "Projekte",
  "targetSkills": "Skills",
  "targetAboutMe": "Über mich",
  "targetTalksEvents": "Vorträge",
  "targetContact": "Kontakt",
  "targetImprint": "Impressum",
  "targetPrivacy": "Datenschutz",
  "targetOtherLanguage": "English",
  "targetOtherLanguageTitle": "Change language to English",
  "introHeading": "Begeistere deine Kunden im Internet!",
  "intro": "Ich bin Ingo Steinke, nachhaltiger und kreativer Webentwickler mit über 20 Jahren Berufserfahrung. Von meiner Arbeit profitierten unter anderem",
  "spacedAnd": " und",
  "commaEnglishOnly": "",
  "currentlyEcologicalIam": "Aktuell arbeite ich vorrangig für Kund:innen mit ökologischem und ethischem Fokus. Ich bin",
  "memberOf": "Mitglied im",
  "careAboutGoingBeyond": "Kreativität, Flexibilität und Reflektiertheit sind mir beruflich und privat sehr wichtig. Ich möchte Nachhaltigkeit, Kultur und Kunst verbinden und neue Erfahrungen in meine tägliche Arbeit einbringen.",
  "workWithMeHeading": "Mit mir kannst du arbeiten.",
  "workWithMe":"Du möchtest deine Website überarbeiten? Dein Team braucht Verstärkung durch einen Frontend-Entwickler mit Fullstack-Erfahrung?",
  "ctaContact": "Ruf mich an oder hinterlasse mir eine Nachricht!",
  "workWithMe2": "Gern können wir uns bei einem Kaffee, telefonisch oder per Zoom unverbindlich über dein Projekt unterhalten.",
  "projectsHeading": "Web- und Software-Projekte",
  "projects": "Überzeuge dich selbst von meiner Arbeit! Eine Auswahl meiner bisherigen Projekte:",
  "projectsScreenshots": "Screenshots",
  "projectPortfolioRelaunchHeading": "Portfolio Relaunch",
  "projectPortfolioRelaunch1": "",
  "projectPortfolioRelaunch2": "Ingo-Steinke.de",
  "projectPortfolioRelaunch3": "zeigt meine Arbeit als Webentwickler. Minimalistisches Design, moderne Typographie, aktuelle Technologie und umfangreiche textliche Überarbeitung prägen den Relaunch meines beruflichen Portfolios. Code:",
  "projectPortfolioRelaunchHashtag1": "HTML 5",
  "projectPortfolioRelaunchHashtag2": "CSS 3",
  "projectPortfolioRelaunchHashtag3": "JavaScript",
  "projectPortfolioRelaunchHashtag4": "Liquid",
  "projectPortfolioRelaunchHashtag5": "Eleventy",
  "projectAtomicRelaunchHeading": "Atomic Design System",
  "projectAtomicRelaunch1": "Als Senior Lead Developer entwickelte ich mit einem Team von Frontend-Webentwicklern ein modulares Design System für den Relaunch mehrerer Websites eines international tätigen Kunden.",
  "projectAtomicRelaunch2": "Als technische Basis diente das Framework",
  "projectAtomicRelaunch3": "Fractal",
  "projectAtomicRelaunch4": ".",
  "projectAtomicRelaunchHashtag1": "HTML",
  "projectAtomicRelaunchHashtag2": "CSS",
  "projectAtomicRelaunchHashtag3": "Fractal",
  "projectAtomicRelaunchHashtag4": "Handlebars",
  "projectAtomicRelaunchHashtag5": "Webpack",
  "projectWandelpunktHeading": "Optimierung und Erweiterung",
  "projectWandelpunkt1": "Diverse bestehende WordPress-Websites erweiterte ich um neue Inhalte und optimierte die Ladezeit und Barrierefreiheit, unter anderem das mit dem Semplice Page Builder für WordPress erstellte Design System der SDG-Berater*innen von",
  "projectWandelpunkt2": "Wandelpunkt-Consulting.de",
  "projectWandelpunkt3Spaced": "",
  "projectWandelpunktHashtag1": "WordPress",
  "projectWandelpunktHashtag2": "Semplice",
  "projectWandelpunktHashtag3": "CSS",
  "projectWandelpunktHashtag4": "SVG",
  "projectWordpressWooHeading": "WooCommerce-Shop",
  "projectWordpressWoo1": "Den nachhaltigen Lebensmittelversand",
  "projectWordpressWoo2": "unterstütze ich bei der Weiterentwicklung des Full Site Editing Block Themes für ihren WooCommerce-Shop",
  "projectWordpressWooHashtag1": "WordPress",
  "projectWordpressWooHashtag2": "WooCommerce",
  "projectWordpressWooHashtag3": "PHP",
  "projectWordpressWooHashtag4": "CSS",
  "projectShopwarePluginHeading": "Shopware-Plugin",
  "projectShopwarePlugin1": "Shopbetreibern wird durch eine API-Schnittstelle die Ladezeit-Optimierung erleichtert. Dieses Administration-Plugin war mein erstes Projekt mit Shopware 6 und wurde 2020",
  "projectShopwarePlugin2": "im offiziellen Shopware-Store",
  "projectShopwarePlugin3": "veröffentlicht.",
  "projectShopwarePluginHashtag1": "Shopware 6",
  "projectShopwarePluginHashtag2": "Symfony",
  "projectShopwarePluginHashtag3": "PHP",
  "projectShopwarePluginHashtag4": "Vue.js",
  "projectReactAppHeading": "React-Web-App",
  "projectReactApp1": "Die grafischen Oberfläche von wao.io visualisierte technische Daten und ließ Webmaster die Optimierung ihrer Website selbst einstellen. Ich entwickelte und aktualisierte Komponenten der Web-App",
  "projectReactApp2": "als Teil des Frontend- und Support-Teams",
  "projectReactApp3": "",
  "projectReactAppHashtag1": "React",
  "projectReactAppHashtag2": "JSX",
  "projectReactAppHashtag3": "ES6",
  "projectReactAppHashtag4": "CSS-in-JS",
  "projectReactAppHashtag5": "Storybook",
  "projectWebperfTalkHeading": "Performance-Vortrag",
  "projectWebperfTalk1": "Wie beschleunige ich meine Website? Angelina Farsch und ich",
  "projectWebperfTalk2": "erläuterten beim Kölner Web-Performance-Meetup",
  "projectWebperfTalk3": ", wie wir herausfinden, ob Wesbites zu den Sprintern oder Schnecken gehören und wodurch wir die Performance erhöhen können.",
  "projectWebperfTalkHashtag1": "Meetup",
  "projectWebperfTalkHashtag2": "Vortrag",
  "projectWebperfTalkHashtag3": "Jitsi",
  "projectKleiderordnungHeading": "Sustainable Fashion Website",
  "projectKleiderordnung1": "",
  "projectKleiderordnung2": "Kleiderordnung.Berlin",
  "projectKleiderordnung3": "ist eine WordPress-Website für die nachhaltige Modeberaterin Tina Steinke mit individueller Startseite nach grafischen Entwürfen von Ina Nixdorf.",
  "projectKleiderordnungCode": "Quellcode:",
  "projectKleiderordnungHashtag1": "HTML",
  "projectKleiderordnungHashtag2": "CSS",
  "projectKleiderordnungHashtag3": "JavaScript",
  "projectKleiderordnungHashtag4": "PHP",
  "projectKleiderordnungHashtag5": "WordPress",
  "projectDaskannstdutunHeading": "Klimapsychologiekampagne",
  "projectDaskannstdutun1": "Als Teamarbeit von",
  "projectDaskannstdutunAnd": "und",
  "projectDaskannstdutunCreatedSpaced": " entstand die Website",
  "projectDaskannstdutunDKDT": "Das kannst du tun",
  "projectDaskannstdutunLast": "mit weiterführenden Informationen zur gleichnamigen gemeinnützigen Werbekampagne. Ich optimierte die responsive Darstellung.",
  "projectDaskannstdutunHashtag1": "WordPress",
  "projectDaskannstdutunHashtag2": "Elementor",
  "projectDaskannstdutunHashtag3": "CSS",
  "projectPlantedHeading" : "Frontend-Erweiterung",
  "projectPlanted1": "Nach einem gemeinsamen Projekt beim",
  "projectPlanted2": "ClimateHack",
  "projectPlanted3": "2021 unterstützte ich das Kölner Startup",
  "projectPlanted4": "Planted",
  "projectPlanted5": "unter anderem bei der Integration von Zahlungsdienstleistern in Webflow und bei der Einarbeitung einer neuen Mitarbeiterin.",
  "projectPlantedHashtag1": "Webflow",
  "projectPlantedHashtag2": "JavaScript",
  "projectPlantedHashtag3": "HTML",
  "projectPlantedHashtag4": "CSS",
  /* work */
  "workHeading": "Langlebige Lösungen",
  "work": "Deine Layouts realisiere ich plattformübergreifend, responsiv und barrierefrei. Mein Ziel sind langlebige Lösungen, elegant, verständlich und pflegeleicht. Modulare Komponenten, Themes, sowie CSS-Frameworks und Methoden wie BEM und Atomic Design erleichtern die Teamarbeit und Weiterentwicklung. Kontinuierliches Testen ermöglicht mir, Fehler frühzeitig zu entdecken und zu beheben.",
  "workReliableHeading": "Zuverlässig und verständlich",
  "workReliable": "Mir ist es wichtig, technische Themen einfach verständlich zu erklären, die Wünsche meiner Kundschaft zu verstehen, weiterzudenken und nachhaltig umzusetzen.",
  "workClientsBenefit": "Als Kund:in profitierst du von geringeren Wartungskosten, optimierter Performance und erfolgreicher Kund:innenansprache.",
  "pricingHeading": "Preise",
  "pricing": "Ich biete verschiedene Preismodelle an. Bei einer Abrechnung auf Stundenbasis gebe ich üblicherweise im Vorfeld eine Aufwandsschätzung ab. Festpreisangebote sind ebenfalls möglich. Mein Stundensatz richtet sich nach Art und Umfang der Tätigkeit und beginnt ab <span class=price>85,- €</span> (zzgl. 19% MWSt.) Gemeinnützige Organisationen und nachhaltige Startups können auf Anfrage vergünstigte Angebote erhalten.",
  "workFullstackHeading": "Full-Stack-Erfahrung und Frontend-Fokus",
  "workFullstack": "Bei der Weiterentwicklung bestehenden Codes kommt mir meine Berufserfahrung und meine pragmatische Einstellung zugute. Mit meinen Erfahrungen im Backend- und DevOps-Bereich und meiner hohen Lernbereitschaft übernehme ich bei Bedarf alle Aufgaben, die sich bei der Webentwicklung ergeben oder finde geeignete Partner:innen für die Umsetzung.",
  "workOwnFocus": "Mein Schwerpunkt ist die Frontend-Entwicklung mit CSS.",
  "workCertifiedHeading": "Zertifizierte E-Commerce-Entwicklung",
  "workCertifiedIam": "Ich bin",
  "workCertifiedSWDev": "zertifizierter Shopware 6 Developer",
  "workCertifiedPdfUrl": "Shopware-6-Certified-Developer-Ingo-Steinke-de.pdf",
  "workCertifiedAnd": "und",
  "workCertifiedExtensionPartner": "Shopware Extension Partner",
  "workTeamHeading": "Team / Netzwerk",
  "workTeam": "Ich habe kein festes Team, aber ein Netzwerk guter Geschäftsfreund:innen mit denen ich teilweise schon seit vielen Jahren zusammenarbeite. Als Kund:in kannst du mir aber auch gerne die Dienstleister:innen deines Vertrauens vorstellen. So behältst du selbst die volle Kontrolle und sparst dir Mehraufwand und wechselnde Ansprechpartner:innen klassischer Agenturen.",
  "workPluginsHeading": "Open Source / Plugin-Programmierung",
  "workPlugins1": "Schnittstellen zum Backend implementiere ich vorzugsweise als unabhängige Open-Source-Module.",
  "workPlugins5": "Aktuell arbeite ich an WordPress-Plugins zur",
  "workPlugins6": "vorzeitigen Erkennung von Plugin-Konflikten",
  "workPluginsAnd": "und",
  "workPlugins7": "zum Spam-Bericht für WordPress-Kontaktformulare",
  "workPluginsOther": "Zudem entwickelte ich Erweiterungen und Themes für Shopware, WebStorm und IntelliJ IDEA, unter anderem das kostenlos erhätliche",
  /* Skills */
  "SkillsHeading": "Fachkenntnisse (Skills)",
  "SkillsWebdevHeading": "Webentwicklung",
  "SkillsWebdevDb": "Datenbanken",
  "SkillsLib": "Software Stacks",
  "SkillsLibStaticSiteGenerators": "SSG",
  "SkillsLibDesignSystems": "Design-Systeme",
  "SkillsOther": "Sonstige Tools",
  "SkillsOtherQa": "Qualitätssicherung, Tests und Audits",
  "SkillsOtherVcs": "Codeverwaltung, Versionierung",
  "SkillsOtherLinter": "Linter, Bundler, Transpiler",
  "SkillsOtherDevops": "DevOps, Automatisierung",
  "SkillsDevuxImg": "Kollaboration, Projektmanagement",
  "SkillsOtherImg": "Bildbearbeitung, Bildoptimierung",
  /* About me, talks, and events */
  "aboutMeHeading": "Beruf und Leidenschaft",
  "aboutMeIntroHeading": "Was mich immer noch fasziniert",
  "aboutMeIntro": "Weltweite Kommunikation und Inspiration: das World Wide Web verbindet die Menschen mithilfe robuster und dezentraler Technologie. Schöne, schnelle und barrierefreie Websites sollen allen Menschen Zugang zu diesem Netzwerk bieten. Meine Arbeit trägt dazu bei, diesen Traum zu verwirklichen.",
  "aboutMeCvHeading": "Werdegang",
  "aboutMeCv1": "Interaktive Websites und Browserspiele waren die ersten Produkte meines 2000 mitgegründeten Startups in Münster. Suchmaschinenoptimierung und unsere CMS- und Shop-Software Active-Webshop bildeten später das Kerngeschäft.",
  "aboutMeCv2": "Als angestellter E-Commerce-Engineer bei Xsite in Düsseldorf entwickelte ich von 2010 bis 2014 Online-Shops für Shop-Apotheke.com, den Kunstversand Ars mundi und andere Kunden. Als Technical Consultant bei Sevenval Technologies (später Avenga Germany) in Köln und Berlin optimierte ich die Ladezeit und Handytauglichkeit von Apps und Websites der Frankfurter Allgemeinen Zeitung und Online-Shops der Otto Group und erstellte Frontend-Anwendungen für wao.io und andere Kunden. Seit Ende 2020 bin ich als selbstständiger Webentwickler und Freelancer unter anderem für nexum, FoodTogether und Planted tätig.",
  "aboutMeEthicalHeading": "Zukunftsthemen und nachhaltige Digitalisierung",
  "aboutMeEthical": "Innovation, Transformation und Digitalisierung bedeuten in der IT-Branche oft nur technologischen Fortschritt. Gesellschaftlichen Herausforderungen in der Ökologie, Gleichberechtigung, Teilhabe, Sicherheit und Datenschutz fehlt oft die nötige Priorität. Ethische und ökologische Projekte beispielsweise in der Verkehrswende, bei erneuerbaren Energien und umweltfreundlicher Mode möchte ich mit meiner Arbeit bevorzugt unterstützen.",
  "aboutMeEthicalImA": "Ich bin ein",
  "aboutMeEthicalA": "ein",
  "aboutMeEthicalandASignatory": " und unterzeichnete das",
  "aboutMeAtDev": "In meinem",
  "aboutMeDevBlog": "DEV Blog",
  "aboutMeAndOn": "und auf",
  "aboutMeOMCLinkText": "Open-Mind-Culture.org",
  "aboutMeIRegularly": "veröffentliche ich regelmäßig Artikel über Webentwicklung und damit zusammenhängende technologische und gesellschaftliche Themen.",
  "talksHeading": "Vorträge, Veranstaltungen, Kund:innenstimmen",
  "talksImageAlt": "Foto: Ingo Steinke, Frontend Web Developer, Freelancer, auf never code alone TV in 2021: Wenn ich denke, ich weiß immer besser, dann kommt jemand anders und sagt: Hey das kannst...",
  "talksImageCaption": "Bild",
  "talksImageLinkText": "Never Code Alone Conference 2021",
  "talks": "Konferenzen, Kurse und Meetups bieten gelegenheit zu fachlichem und persönlichem Austausch.",
  "talks2": "In den letzten Jahren hielt ich unter anderem diese Vorträge:",
  "talkMeetupWebVitals": "Core Web Vitals: Web Performance and Usability",
  "talkMeetupWebVitals2": ", 2021",
  "talkMeetupsCorona": "Meetups in Zeiten von Corona",
  "talkMeetupsCorona2": ", 2020",
  "talkPerformanceNoCode": "Performance-Optimierung ohne Code-Änderung",
  "talkPerformanceNoCode2": ", 2020 (mit Angelina Farsch)",
  "talkHsts": "HSTS: Mehr Sicherheit ohne Performanceverlust",
  "talkHsts2": ", 2018",
  "talkInfrastructure": "Infrastruktur für bessere Web Performance",
  "talkInfrastructure2": ", 2017",
  "testimonials": "Kund:innenfeedback",
  "testimonialsReadMoreText1": "Weitere Bewertungen bei Google Business",
  "testimonialsReadMoreTextAnd": "und",
  "testimonialsReadMoreText2": "ProvenExpert lesen",
  "testimonialsReadMoreLinkUrl1": "https://www.google.com/maps/place/Ingo+Steinke/@54.5871961,-51.7559002,3z/data=!4m13!1m3!11m2!2s1A_qFX3OC2-87_jFnYtJquSLGNds!3e1!3m8!1s0x47b8cf81dc94e4ab:0x756104e1aec1a165!8m2!3d52.4789132!4d13.4417945!9m1!1b1!15sCgEqWgMiASqSARB3ZWJzaXRlX2Rlc2lnbmVy4AEA!16s%2Fg%2F11qsm5r_br",
  "testimonialsReadMoreLinkUrl2": "https://www.provenexpert.com/ingo-steinke-creative-web-developer/",
  "testimonialDanielaQuote": "Ich hatte das Vergnügen mit Ingo zusammenzuarbeiten und bin begeistert von seiner Kompetenz im Bereich Webentwicklung. Er ist nicht nur technisch versiert, sondern auch konzeptionell stark. Besonders eindrucksvoll finde ich, dass Ingo für jedes Problem eine Lösung erarbeiten kann. Nicht zuletzt zeichnet er sich durch sein starkes Engagement im Bereich Nachhaltigkeit aus.",
  "testimonialDanielaAuthor": "Daniela, Designerin",
  "testimonialDanielaLinkUrl": "https://danielagaulrapp.com",
  "testimonialMalteQuote": "An meiner Seite haben bereits einige Programmierer und ITler gewerkelt, aber erst jetzt merke ich was für einen krassen Unterschied es machen kann.",
  "testimonialMalteAuthor": "Malte, Fotograf",
  "testimonialMalteLinkUrl": "https://www.malte-reiter.de",
  "testimonialPatriciaQuote": "Wir sind total zufrieden mit Ingo. Absolut zuverlässig und tolle Ergebnisse. 100% Empfehlung!",
  "testimonialPatriciaAuthor": "Patricia, systemischer Coach",
  "testimonialPatriciaLinkUrl": "https://www.moock-coaching.de",
  /* Interested CTA */
  "interestedHeading": "Interessiert?",
  "interested": "Melde dich gerne, um ein unverbindliches Gespräch zu vereinbaren! Anfragen werden zeitnah beantwortet! Ich bin telefonisch, per E-Mail, per Signal oder WhatsApp erreichbar. Falls ich einen Anruf nicht persönlich entgegennehmen kann, hinterlasse mir gerne eine Sprachnachricht!",
  /* Imprint, Contact */
  "imprintHeader": "Impressum und Kontaktdaten",
  "imprintName": "Ingo Steinke",
  "imprintRole": "Webentwickler",
  "imprintStreetAddress": "Donaustr. 83 II",
  "imprintPostalCode": "12043",
  "imprintCity": "Berlin",
  "imprintCountryName": "Deutschland",
  "postalAddressLabel": "Postanschrift",
  "untilDec22": "bis 31.12.2022",
  "contactTel": "+491634684080",
  "contactTelChunks": [
    "+49",
    "163",
    "46",
    "84",
    "08",
    "0"
  ],
  "contactTelOfflineLabel": "Telefon zeitweise nicht erreichbar",
  "contactInterimLabel": "übergangsweise stattdessen",
  "contactEmail": "kontakt@ingo-steinke.de",
  "taxNo": "Steuernr.",
  "vatIdLabel": "UStID",
  "vatIdNumber": "DE337676808",
  "insurance": "Berufshaftpflichtversicherung: Media-Haftpflicht",
  "insuranceTitle": "Berufshaftpflichtversicherung: exali Media-Haftpflicht",
  "bankaccountLabel": "Bankverbindung: GLS Gemeinschaftsbank eG",
  "bankaccountNumberChunks": [
    "DE89",
    "4306",
    "0967",
    "3029",
    "8400",
    "00"
  ],
  "profile": "Profil",
  "at": "auf",
  "vcardQrTitle": "Ingo-Steinke als Kontakt speichern",
  "vcardQrImgAlt": "QR-Code: Kontakt zu Ingo-Steinke",
  "vcardQrImgFilename": "ingo-steinke-de-vcard-qr.svg",
  "scanAndSaveContact1": "Kontakt scannen",
  "scanAndSaveContact2": "und speichern",
  "privacyGdpr": "Die Regeln des Bundesdatenschutzgesetzes (BDSG) und der europäischen Datenschutzgrundverordnung (DSGVO) sind Anlass zu dieser Datenschutzerklärung. Das",
  "privacyGdprImprint": "Impressum",
  "privacyGdpr2": "nennt den verantworlichen Anbieter und deine Möglichkeiten zur Kontaktaufnahme.",
  "privacyYourRightsHeading": "Dein gutes Recht: Auskunft, Korrektur, Löschung, Widerruf",
  "privacyYourRights": "Du hast das Recht, eine Einwilligung in die Verarbeitung deiner Daten zu verweigern oder nachträglich zu widerrufen, sowie das Recht auf Auskunft hinsichtlich der über deine Person gespeicherten Daten und können eine Löschung dieser Daten oder eine Korrektur unzutreffender Daten verlangen. Ausgenommen von der Löschung sind gespeicherte Daten, die der gesetzlichen Aufbewahrungspflicht bzw. der steuerlichen Abgabenordnung oder einer anderweitig vorgeschriebenen Datenspeicherung zur Geschäftsabwicklung unterliegen.",
  "privacyPersonalDataHeading": "Umfang der Verarbeitung personenbezogener Daten",
  "privacyPersonalData": "Personenbezogene Daten meiner Nutzer verarbeite ich grundsätzlich nur soweit, wie dies zur Vertragserfüllung, zu konkreten vorvertraglichen Vereinbarungen, sowie zur Bereitstellung einer funktionsfähigen Website erforderlich ist. Die Verarbeitung personenbezogener Daten meiner Nutzer erfolgt nur nach Einwilligung der Nutzerin bzw. des Nutzers, außer in solchen Fällen, in denen eine vorherige Einholung einer Einwilligung aus tatsächlichen Gründen nicht möglich ist und die Verarbeitung der Daten durch gesetzliche Vorschriften ausdrücklich gestattet oder gefordert ist.",
  "privacyLawHeading": "Rechtsgrundlage für die Verarbeitung personenbezogener Daten",
  "privacyLaw": "Bei der Verarbeitung von personenbezogenen Daten, die zur Erfüllung eines Vertrages mit der betroffenen Person als Vertragspartei erforderlich ist, dient Art. 6 Abs. 1 Bst. b DSGVO als Rechtsgrundlage. Dies gilt auch für Verarbeitungsvorgänge, die zur Durchführung vorvertraglicher Maßnahmen erforderlich sind.",
  "privacyLaw2": "Soweit eine Verarbeitung personenbezogener Daten zur Erfüllung einer rechtlichen Verpflichtung erforderlich ist, dient Art. 6 Abs. 1 Bst. c DSGVO als Rechtsgrundlage.",
  "privacyMinimalHeading": "Datensparsamkeit und Datenminimierung",
  "privacyMinimal": "Personenbezogene Daten speichere ich gemäß den Grundsätzen der Datenvermeidung und Datensparsamkeit nur so lange, wie es erforderlich ist oder vom Gesetzgeber her vorgeschrieben wird (gesetzliche Speicherfrist). Entfällt der Zweck der erhobenen Informationen oder endet die Speicherfrist, veranlasse ich die Sperrung bzw. Löschung der Daten.",
  "privacyNoCookies": "Diese Website verwendet keine Cookies. Auf dieser Website verzichte ich zudem auf Auswertungs- und Werbefunktionen externer Anbieter. Daher werden auch keinerlei Daten mit Google Analytics, Facebook oder ähnlichen Drittanbietern ausgetauscht.",
  "privacyLinkDisclaimer": "Verweise zu sozialen und beruflichen Netzwerken sind lediglich Links zu externen Anbietern. Anzeigen und Ansehen der dieser Verweise führt zu keiner Datenübertragung an Drittanbieter.",
  "privacyLogfilesHeading": "Bereitstellung der Website und Auswertung technischer Daten (Logfiles)",
  "privacyLogfiles": "Mit jedem Zugriff auf dieses Angebot werden durch mich beziehungsweise die von mir beauftragten Web-Provider und deren Dienstleister automatisch Informationen erfasst, die zur technischen Bereitstellung der Website erforderlich sind. Erfasst werden die Adresse der besuchten Website, Datum und Uhrzeit, übertragene Datenmenge, Webbrowserkennung, IP-Adresse und gegebenenfalls auf die aufgerufene Website verweisende Websites. Die Daten werden in den Logfiles der EDV gespeichert. Eine Speicherung dieser Daten zusammen mit anderen personenbezogenen Daten der Nutzer findet nicht statt. Eine Auswertung der Daten zu Marketingzwecken findet in diesem Zusammenhang ebenfalls nicht statt.",
  "privacyLogfilesLaw": "Rechtsgrundlage für die vorübergehende Speicherung dieser Daten und der Logfiles ist Art. 6 Abs. 1 Bst. f DSGVO. Die Speicherung in Logfiles erfolgt, um die Funktionsfähigkeit der Website sicherzustellen. Zudem dienen diese Daten zur Gewährleistung der Sicherheit der informationstechnischen Systeme. Ich behalte mir das Recht vor, die Server-Logfiles bei Verdacht auf eine rechtswidrige Nutzung meines Angebotes nachträglich zu kontrollieren.",
  "privacyChangesHeading": "Änderung dieser Datenschutzerklärung",
  "privacyChanges": "Um zu gewährleisten, dass diese Datenschutzerklärung stets den aktuellen gesetzlichen Vorgaben entspricht, behalte ich mir jederzeit Änderungen vor. Das gilt auch für den Fall, dass die Datenschutzerklärung aufgrund neuer oder überarbeiteter Leistungen, zum Beispiel neuer Serviceleistungen, angepasst werden muss. Die neue Datenschutzerklärung greift dann bei deinem nächsten Besuch auf meinem Angebot.",
  "ecofriendlyGreenWebCheckUrl": "https://www.thegreenwebfoundation.org/green-web-check/?url=https%3A%2F%2Fwww.ingo-steinke.de%2F",
  "ecofriendlyGreenWebCheckImageFilename": "badge-greencheckimage-www.ingo-steinke.de-2023",
  "ecofriendlyGreenWebCheckImageOriginalSrc": "https://api.thegreenwebfoundation.org/greencheckimage/www.ingo-steinke.de?nocache=true",
  "ecofriendlyGreenWebCheckImageAlt": "This website is hosted Green by goneo Internet GmbH - checked by thegreenwebfoundation.org",
  "ecofriendlyEcograderUrl": "https://ecograder.com/report/xIVJ8Ub1j74pqr6JQ45iClLA",
  "ecofriendlyEcograderTitle": "In October 2023, this page scored better than 89% of all URLs crawled by Ecograder.",
  "ecofriendlyEcograderScore": "Ecograder Score: 97/100 (0.05 g CO₂e)",
  "listedAt": "Verzeichnet bei",
  "buttonStopAnimation": "Animation ausblenden",
  "buttonStartAnimation": "Animation einblenden",
  "buttonToggleAnimation": "Animation an/aus",
  "updatedWithColon": "aktualisiert am",
  "dotIfGerman": ".",
  "toggleHighContrast": "Kontrast ändern",
  "reduceContrast": "Kontrast verringern",
  "increaseContrast": "Kontrast erhöhen",
  "showLandingpageLinks": "true",
  "landingLinkTitleWordPress":"Wordpress-Website nachhaltig optimieren lassen",
  "landingLinkTextWordPress": "WordPress",
  "landingLinkUrlWordPress": "https://www.ingo-steinke.de/wordpress-website-nachhaltig-optimieren-lassen/",
  "landingLinkTitleShopware": "Zertifizierter Shopware 6 + Frontend Webentwickler",
  "landingLinkTextShopware": "Shopware",
  "landingLinkUrlShopware": "https://www.ingo-steinke.de/zertifizierter-shopware-6-frontend-webentwickler/",
  "landingLinkTitleSustainability": "Webseiten klimafreundlich und barrierefrei optimieren lassen",
  "landingLinkTextSustainability": "Nachhaltigkeit",
  "landingLinkUrlSustainability": "https://www.ingo-steinke.de/webseiten-klimafreundlich-barrierefrei-optimieren/"
};


