/* de/content.js
 * GERMAN LANGUAGE CONTENT for ingo-steinke.de
 */
module.exports = {
  /* meta data */
  "language": "de",
  "canonicalHref": "https://www.ingo-steinke.de/",
  "alternateHreflang": "en",
  "alternateHref": "https://www.ingo-steinke.com/",
  "metaAuthor": "Ingo Steinke",
  "pageTitle": "Ingo Steinke, dein kreativer Webentwickler in Düsseldorf",
  "pageDescription": "Ingo Steinke ist ein kreativer Webentwickler in Düsseldorf mit über 20 Jahren Beruferfahrung.",
  "pageDescription-en": "Ingo Steinke is a creative front-end web developer in Düsseldorf.",
  "pageKeywords": "Ingo,Steinke,Webentwickler,Berater,Düsseldorf",
  "pDomainVerify": "4c4296e5835f4a47eb2c2e5488a99d71",
  "googleSiteVerification": "Qs1p7JgqPLOGD3BYCMGe9EbyNJJEswyala44hnkO6d4",
  /* page content */
  "jumbotronImageAlt": "Portrait of Ingo Steinke",
  "jumbotronHeader": "Ingo Steinke",
  "jumbotronTagline": "Creative Web Developer",
  "linkToTop": "Zum Seitenanfang",
  "menuLabel": "Inhaltsverzeichnis",
  "menuOpen": "Inhaltsverzeichnis öffnen",
  "menuClose": "Inhaltsverzeichnis schließen",
  "menuButton": "Inhalt",
  "targetProjects": "Projekte",
  "targetSkills": "Skills",
  "targetAboutMe": "Über mich",
  "targetTalksEvents": "Vorträge",
  "targetContact": "Kontakt",
  "targetImprint": "Impressum",
  "targetPrivacy": "Datenschutz",
  "targetOtherLanguage": "English",
  "targetOtherLanguageTitle": "Change language to English",
  "introHeading": "Begeistere deine Kunden im Internet",
  "intro": "Ich bin Ingo Steinke, nachhaltiger und kreativer Webentwickler mit über 20 Jahren Berufserfahrung. Von meiner Arbeit profitierten unter anderem die",
  "and": "und",
  "workWithMeHeading": "Mit mir kannst du arbeiten",
  "workWithMe":"Du möchtest deine Website überarbeiten? Dein Team braucht Verstärkung durch einen Frontend-Entwickler mit Fullstack-Erfahrung?",
  "ctaContact": "Ruf mich an oder hinterlasse mir eine Nachricht!",
  "workWithMe2": "Gern können wir uns bei einem Kaffee unverbindlich über dein Projekt unterhalten.",
  "projectsHeading": "Projekte",
  "projects": "Überzeuge dich selbst von meiner Arbeit! Eine Auswahl meiner bisherigen Projekte:",
  "projectPortfolioRelaunchHeading": "Portfolio Relaunch",
  "projectPortfolioRelaunch1": "",
  "projectPortfolioRelaunch2": "Ingo-Steinke.de",
  "projectPortfolioRelaunch3": "zeigt meine Arbeit als Webentwickler. Modernes Design und Typographie, aktuelle Technologie und umfangreiche textliche Überarbeitung prägen den Relaunch meines beruflichen Portfolios. Code:",
  "projectPortfolioRelaunch4": "github.com/openmindculture/ingo-steinke.de",
  "projectPortfolioRelaunchHashtag1": "HTML 5",
  "projectPortfolioRelaunchHashtag2": "CSS 3",
  "projectPortfolioRelaunchHashtag3": "JavaScript",
  "projectPortfolioRelaunchHashtag4": "Liquid",
  "projectPortfolioRelaunchHashtag5": "Eleventy",
  "projectWebperfMeetupHeading": "Meetup-Organisation",
  "projectWebperfMeetup1": "Anfang 2020 übernahm ich die fachliche Leitung des",
  "projectWebperfMeetup2": "Kölner Web-Performance-Meetups",
  "projectWebperfMeetup3": "Diverse internationale Vorträge, unter anderem von Patrick Meenan, Andrew Petryk, Anna Backs und Christina Zenzes begeisterten das Publikum über die Grenzen der Region hinaus.",
  "projectWebperfMeetupHashtag1": "Event-Management",
  "projectWebperfMeetupHashtag2": "Web-Performance",
  "projectWordpressPluginHeading": "WordPress-Plugin",
  "projectWordpressPlugin1": "Als Arbeitserleichterung für die Redakteure unserer Kunden bereinigt ein WordPress-Plugin vollautomatisch den Cache-Speicher des Servers, auf dem wao.io die Ladezeit der WordPress-Seite optimiert. Das Plugin wurde 2020",
  "projectWordpressPlugin2": "auf WordPress.org",
  "projectWordpressPlugin3": "veröffentlicht.",
  "projectWordpressPluginHashtag1": "PHP",
  "projectWordpressPluginHashtag2": "JavaScript",
  "projectWordpressPluginHashtag3": "Docker",
  "projectWordpressPluginHashtag4": "Localization",
  "projectShopwarePluginHeading": "Shopware-Plugin",
  "projectShopwarePlugin1": "Shopbetreibern wird durch eine API-Schnittstelle die Ladezeit-Optimierung erleichtert. Dieses Administration-Plugin war mein erstes Projekt mit Shopware 6 und wurde 2020",
  "projectShopwarePlugin2": "im offiziellen Shopware-Store",
  "projectShopwarePlugin3": "veröffentlicht.",
  "projectShopwarePluginHashtag1": "Shopware 6",
  "projectShopwarePluginHashtag2": "Symfony",
  "projectShopwarePluginHashtag3": "PHP",
  "projectShopwarePluginHashtag4": "Vue.js",
  "projectReactAppHeading": "React-Web-App",
  "projectReactApp1": "Die grafischen Oberfläche von wao.io visualisiert technische Daten und lässt Webmaster die Optimierung deiner Website selbst einstellen. Ich entwickelte und aktualisierte Komponenten der Web-App",
  "projectReactApp2": "als Teil des Frontend- und Support-Teams",
  "projectReactApp3": ".",
  "projectReactAppHashtag1": "React",
  "projectReactAppHashtag2": "JSX",
  "projectReactAppHashtag3": "ES6",
  "projectReactAppHashtag4": "CSS-in-JS",
  "projectReactAppHashtag5": "Storybook",
  "projectWebperfTalkHeading": "Performance-Vortrag",
  "projectWebperfTalk1": "Wie beschleunige ich meine Website? Angelina Farsch und ich",
  "projectWebperfTalk2": "erläuterten beim Kölner Web-Performance-Meetup",
  "projectWebperfTalk3": ", wie wir herausfinden, ob Wesbites zu den Sprintern oder Schnecken gehören und wodurch wir die Performance erhöhen können.",
  "projectWebperfTalkHashtag1": "Meetup",
  "projectWebperfTalkHashtag2": "Vortrag",
  "projectWebperfTalkHashtag3": "Jitsi",
  "projectKleiderordnungHeading": "Web-Visitenkarte",
  "projectKleiderordnung1": "",
  "projectKleiderordnung2": "Kleiderordnung-Duesseldorf.de",
  "projectKleiderordnung3": "entwickelte ich 2016 als One-Pager mit Reiternavigation. Grafische Grundlage war das vorliegende Design der gedruckten Flyer und Visitenkarten, das ich in Absprache mit der Designerin für die Website adaptierte.",
  "projectKleiderordnungHashtag1": "HTML 5",
  "projectKleiderordnungHashtag2": "CSS 3",
  "projectKleiderordnungHashtag3": "JavaScript",
  "projectKleiderordnungHashtag4": "PHP",
  "projectLucomErechnungHeading": "Elektronischer Rechnungseingang",
  "projectLucomErechnung": "2018 implementierte ich als LIP Certified Designer eine Komponente zur Anzeige von eRechnungen mithilfe der Lucom Interaction Platform und Oracle SQL.",
  "projectLucomErechnungHashtag1": "LIP",
  "projectLucomErechnungHashtag2": "JavaScript",
  "projectLucomErechnungHashtag3": "XRechnung",
  "projectLucomErechnungHashtag4": "UBL",
  "projectLucomErechnungHashtag5": "SQL",
  "projectPlantedHeading" : "Frontend-Erweiterung",
  "projectPlanted1": "Nach einem gemeinsamen Projekt beim",
  "projectPlanted2": "ClimateHack",
  "projectPlanted3": "im Februar 2021 unterstützte ich das Kölner Startup",
  "projectPlanted4": "Planted",
  "projectPlanted5": "unter anderem bei der Integration von Zahlungsdienstleistern in Webflow.",
  "projectPlantedHashtag1": "Webflow",
  "projectPlantedHashtag2": "JavaScript",
  "projectPlantedHashtag3": "HTML",
  "projectPlantedHashtag4": "CSS",
  /* work */
  "workHeading": "Langlebige Lösungen",
  "work": "Deine Layouts realisiere ich plattformübergreifend, auf Wunsch auch pixelgenau. Mein Ziel sind langlebige Lösungen, elegant, verständlich und pflegeleicht. Modulare Komponenten, Themes, sowie CSS-Frameworks und Methodiken wie BEM und Atomic Design erleichtern die Zusammenarbeit und Weiterentwicklung. Kontinuierliches Testen ermöglicht es mir, Fehler frühzeitig zu entdecken und zu beheben.",
  "workFullstackHeading": "Full-Stack-Erfahrung",
  "workFullstack": "Bei der Weiterentwicklung bestehenden Codes kommt mir meine Berufserfahrung und meine pragmatische Einstellung zugute. Mit meinen Erfahrungen im Backend- und DevOps-Bereich und meiner hohen Lernbereitschaft übernehme ich bei Bedarf auch Aufgaben, die sich im Umfeld der Frontend-Entwicklung ergeben.",
  "workPluginsHeading": "Plugin-Programmierung",
  "workPlugins1": "Schnittstellen zum Backend implementiere ich vorzugsweise als unabhängige Module. Für den Web-Performance-Servive wao.io entwickelte ich jeweils ein",
  "workSwLink1Text": "Plugin für Shopware 6",
  "workPlugins2": "und",
  "workWpLinkText": "für das CMS WordPress",
  "workPlugins3": ". Beide Plugins wurden nach erfolgreicher Prüfung in die ",
  "workSwLink2Title": "Shopware-Store-Seite für das Plugin wao.io Cache Control",
  "workSwLink2Text": "offiziellen Verzeichnisse ",
  "workPlugins4": "aufgenommen.",
  "workPluginsOther": "Zudem entwickelte ich Themes für Shopware 5 und 6 und für JetBrains-IDEs wie PHPStorm und IntelliJ IDEA.",
  /* Skills */
  "SkillsHeading": "Fachkenntnisse (Skills)",
  "SkillsWebdevHeading": "Webentwicklung",
  "SkillsWebdevDb": "Datenbanken",
  "SkillsLib": "Software Stacks",
  "SkillsOther": "Sonstige Tools",
  "SkillsOtherQa": "Qualitätssicherung",
  "SkillsOtherVcs": "Codeverwaltung",
  "SkillsOtherLinter": "Linter, Transpiler",
  "SkillsOtherDevops": "DevOps",
  "SkillsDevuxImg": "Kollaboration",
  "SkillsOtherImg": "Bildbearbeitung",
  /* About me, talks, and events */
  "aboutMeHeading": "Beruf und Leidenschaft",
  "aboutMeIntroHeading": "Was mich immer noch fasziniert",
  "aboutMeIntro": "Weltweite Kommunikation und Inspiration: das World Wide Web verbindet die Menschen mithilfe robuster und dezentraler Technologie. Schöne, schnelle und zugängliche Websites sollen allen Menschen Zugang zu diesem Netzwerk bieten. Meine Arbeit trägt dazu bei, diesen Traum zu verwirklichen.",
  "aboutMeCvHeading": "Werdegang",
  "aboutMeCv1": "Interaktive Websites und Browserspiele waren die ersten Produkte meines 2000 gegründeten Startups in Münster. Suchmaschinenoptimierung und unsere CMS- und Shop-Software Active-Webshop bildeten später das Kerngeschäft.",
  "aboutMeCv2": "Als angestellter E-Commerce-Engineer bei Xsite in Düsseldorf entwickelte ich von 2010 bis 2014 Online-Shops für Shop-Apotheke.com, den Kunstversand Ars mundi und andere Kunden. Als Technical Consultant bei Sevenval Technologies (später Avenga Germany) in Köln und Berlin optimierte ich die Ladezeit und Handytauglichkeit von Apps und Websites der Frankfurter Allgemeinen Zeitung und erstellte Frontend-Anwendungen für wao.io und andere Kunden. Seit Ende 2020 bin ich selbstständiger Webentwickler.",
  "aboutMeEthicalHeading": "Zukunftsthemen und nachhaltige Digitalisierung",
  "aboutMeEthical": "Innovation, Transformation und Digitalisierung bedeuten in der IT-Branche oft nur technologischen Fortschritt. Gesellschaftlichen Herausforderungen in der Ökologie, Gleichberechtigung, Sicherheit und Datenschutz fehlt oft die nötige Priorität. Ethische und ökologische Projekte beispielsweise in der Verkehrswende, bei erneuerbaren Energien und umweltfreundlicher Mode möchte ich mit meiner Arbeit bevorzugt unterstützen.",
  "aboutMeEthicalImA": "Ich bin ein",
  "aboutMeEthicalA": "ein",
  "aboutMeEthicalandASignatory": " und unterzeichnete das",
  "talksHeading": "Vorträge und Veranstaltungen",
  "talks": "Konferenzen, Kurse und Meetups bieten gelegenheit zu fachlichem und persönlichem Austausch.",
  "talks2": "In den letzten Jahren hielt ich unter anderem diese Vorträge:",
  "talkMeetupWebVitals": "Core Web Vitals: Web Performance and Usability",
  "talkMeetupWebVitals2": ", März 2021",
  "talkMeetupsCorona": "Meetups in Zeiten von Corona",
  "talkMeetupsCorona2": ", Juni 2020",
  "talkPerformanceNoCode": "Performance-Optimierung ohne Code-Änderung",
  "talkPerformanceNoCode2": "mit Angelina Farsch, April 2020",
  "talkHsts": "HSTS: Mehr Sicherheit ohne Performanceverlust",
  "talkHsts2": ", Dezember 2018 beim Kölner Web Performance Meetup",
  "talkInfrastructure": "Infrastruktur für bessere Web Performance",
  "talkInfrastructure2": ", Mai 2017 beim Kölner Web Performance Meetup",
  "talkVocational": "Berufsorientierung: Mein Job! Dein Job?",
  "talkVocational2": ", Januar 2017 am Gymnasium Gerresheim in Düsseldorf",
  /* Imprint, Contact */
  "imprintHeader": "Impressum",
  "imprintName": "Ingo Steinke",
  "imprintStreetAddress": "Neunzigstraße 6a",
  "imprintPostalCode": "40625",
  "imprintCity": "Düsseldorf",
  "imprintCountryName": "Deutschland",
  "imprintTel": "+49 (0) 163 46 84 08 0",
  "contactEmail": "kontakt@ingo-steinke.de",
  "taxNo": "Steuernr.",
  "vatId": "UStID",
  "profile": "Profil",
  "at": "auf",
  "privacyGdpr": "Die Regeln des Bundesdatenschutzgesetzes (BDSG) und der europäischen Datenschutzgrundverordnung (DSGVO) sind Anlass zu dieser Datenschutzerklärung. Das",
  "privacyGdprImprint": "Impressum",
  "privacyGdpr2": "nennt den verantworlichen Anbieter und deine Möglichkeiten zur Kontaktaufnahme.",
  "privacyYourRightsHeading": "Dein gutes Recht: Auskunft, Korrektur, Löschung, Widerruf",
  "privacyYourRights": "Du hast das Recht, eine Einwilligung in die Verarbeitung deiner Daten zu verweigern oder nachträglich zu widerrufen, sowie das Recht auf Auskunft hinsichtlich der über deine Person gespeicherten Daten und können eine Löschung dieser Daten oder eine Korrektur unzutreffender Daten verlangen. Ausgenommen von der Löschung sind gespeicherte Daten, die der gesetzlichen Aufbewahrungspflicht bzw. der steuerlichen Abgabenordnung oder einer anderweitig vorgeschriebenen Datenspeicherung zur Geschäftsabwicklung unterliegen.",
  "privacyPersonalDataHeading": "Umfang der Verarbeitung personenbezogener Daten",
  "privacyPersonalData": "Personenbezogene Daten meiner Nutzer verarbeite ich grundsätzlich nur soweit, wie dies zur Vertragserfüllung, zu konkreten vorvertraglichen Vereinbarungen, sowie zur Bereitstellung einer funktionsfähigen Website erforderlich ist. Die Verarbeitung personenbezogener Daten meiner Nutzer erfolgt nur nach Einwilligung der Nutzerin bzw. des Nutzers, außer in solchen Fällen, in denen eine vorherige Einholung einer Einwilligung aus tatsächlichen Gründen nicht möglich ist und die Verarbeitung der Daten durch gesetzliche Vorschriften ausdrücklich gestattet oder gefordert ist.",
  "privacyLawHeading": "Rechtsgrundlage für die Verarbeitung personenbezogener Daten",
  "privacyLaw": "Bei der Verarbeitung von personenbezogenen Daten, die zur Erfüllung eines Vertrages mit der betroffenen Person als Vertragspartei erforderlich ist, dient Art. 6 Abs. 1 Bst. b DSGVO als Rechtsgrundlage. Dies gilt auch für Verarbeitungsvorgänge, die zur Durchführung vorvertraglicher Maßnahmen erforderlich sind.",
  "privacyLaw2": "Soweit eine Verarbeitung personenbezogener Daten zur Erfüllung einer rechtlichen Verpflichtung erforderlich ist, dient Art. 6 Abs. 1 Bst. c DSGVO als Rechtsgrundlage.",
  "privacyMinimalHeading": "Datensparsamkeit und Datenminimierung",
  "privacyMinimal": "Personenbezogene Daten speichere ich gemäß den Grundsätzen der Datenvermeidung und Datensparsamkeit nur so lange, wie es erforderlich ist oder vom Gesetzgeber her vorgeschrieben wird (gesetzliche Speicherfrist). Entfällt der Zweck der erhobenen Informationen oder endet die Speicherfrist, veranlasse ich die Sperrung bzw. Löschung der Daten.",
  "privacyNoCookies": "Diese Website verwendet keine Cookies. Auf dieser Website verzichte ich zudem auf Auswertungs- und Werbefunktionen externer Anbieter. Daher werden auch keinerlei Daten mit Google Analytics, Facebook oder ähnlichen Drittanbietern ausgetauscht.",
  "privacyLinkDisclaimer": "Verweise zu sozialen und beruflichen Netzwerken sind lediglich Links zu externen Anbietern. Anzeigen und Ansehen der dieser Verweise führt zu keiner Datenübertragung an Drittanbieter.",
  "privacyLogfilesHeading": "Bereitstellung der Website und Auswertung technischer Daten (Logfiles)",
  "privacyLogfiles": "Mit jedem Zugriff auf dieses Angebot werden durch mich beziehungsweise die von mir beauftragten Web-Provider und deren Dienstleister automatisch Informationen erfasst, die zur technischen Bereitstellung der Website erforderlich sind. Erfasst werden die Adresse der besuchten Website, Datum und Uhrzeit, übertragene Datenmenge, Webbrowserkennung, IP-Adresse und gegebenenfalls auf die aufgerufene Website verweisende Websites. Die Daten werden in den Logfiles der EDV gespeichert. Eine Speicherung dieser Daten zusammen mit anderen personenbezogenen Daten der Nutzer findet nicht statt. Eine Auswertung der Daten zu Marketingzwecken findet in diesem Zusammenhang ebenfalls nicht statt.",
  "privacyLogfilesLaw": "Rechtsgrundlage für die vorübergehende Speicherung dieser Daten und der Logfiles ist Art. 6 Abs. 1 Bst. f DSGVO. Die Speicherung in Logfiles erfolgt, um die Funktionsfähigkeit der Website sicherzustellen. Zudem dienen diese Daten zur Gewährleistung der Sicherheit der informationstechnischen Systeme. Ich behalte mir das Recht vor, die Server-Logfiles bei Verdacht auf eine rechtswidrige Nutzung meines Angebotes nachträglich zu kontrollieren.",
  "privacyChangesHeading": "Änderung dieser Datenschutzerklärung",
  "privacyChanges": "Um zu gewährleisten, dass diese Datenschutzerklärung stets den aktuellen gesetzlichen Vorgaben entspricht, behalte ich mir jederzeit Änderungen vor. Das gilt auch für den Fall, dass die Datenschutzerklärung aufgrund neuer oder überarbeiteter Leistungen, zum Beispiel neuer Serviceleistungen, angepasst werden muss. Die neue Datenschutzerklärung greift dann bei deinem nächsten Besuch auf meinem Angebot."
};


