/* de/content.js
 * GERMAN LANGUAGE CONTENT for ingo-steinke.de
 */
module.exports = {
  /* meta data */
  "language": "de",
  "canonicalHref": "https://www.ingo-steinke.de/",
  "canonicalHrefNoTrailingSlash": "https://www.ingo-steinke.de",
  "shortHref": "www.ingo-steinke.de",
  "alternateHreflang": "en",
  "alternateHref": "https://www.ingo-steinke.com/",
  "metaAuthor": "Ingo Steinke",
  "pageTitle": "Ingo Steinke, kreativer Frontend-Webentwickler in Berlin",
  "pageDescription": "Ingo Steinke ist ein kreativer Webentwickler mit Schwerpunkt Frontend, Barrierefreiheit und Nachhaltigkeit, mit über 20 Jahren Beruferfahrung. Auf dieser Website findest du die Leistungen, Preise, Projekte, und was Ingos Kunden sagen.",
  "pageDescription-en": "Ingo Steinke ist ein kreativer Webentwickler mit Schwerpunkt Frontend, Barrierefreiheit und Nachhaltigkeit, mit über 20 Jahren Beruferfahrung. Auf dieser Website findest du die Leistungen, Preise, Projekte, und was Ingos Kunden sagen.",
  "pDomainVerify": "4c4296e5835f4a47eb2c2e5488a99d71",
  "googleSiteVerification": "Qs1p7JgqPLOGD3BYCMGe9EbyNJJEswyala44hnkO6d4",
  "notFoundTitle": "Ingo Steinke - Seite nicht gefunden",
  "notFoundHeading": "Entschuldigung, diese Seite konnten wir nicht finden.",
  "notFoundDescription": "Die gewünschte Seite existiert an dieser Adresse nicht. Aktuelle Links findest du auf meiner ",
  "notFoundHomepageLinkUrl" : "https://www.ingo-steinke.de/",
  "notFoundHomepageLinkText" : "Startseite",
  /* page content */
  "jumbotronImageAlt": "Portrait von Webentwickler Ingo Steinke in Berlin",
  "jumbotronHeader": "Ingo Steinke",
  "jumbotronTagline": "Creative Web Developer",
  "linkToTop": "Zum Seitenanfang",
  "menuLabel": "Inhaltsverzeichnis",
  "menuOpen": "Inhaltsverzeichnis öffnen",
  "menuClose": "Inhaltsverzeichnis schließen",
  "menuButton": "Inhalt",
  "targetProjects": "Projekte",
  "targetProjectsUrl": "projekte/",
  "targetRefs": "Referenzen",
  "targetServices": "Fachkenntnisse",
  "targetServicesTitle": "Leistungen und Fachkenntnisse (Skills)",
  "targetServicesUcFirst": "Fachkenntniss",
  "targetServicesUrl": "leistungen/",
  "targetSkills": "Skills",
  "targetSkillsLong": "Weitere Leistungen und Fachkenntnisse (Skills)",
  "targetAboutMe": "Über mich",
  "targetAboutMeUrl": "ueber-mich.html",
  "targetTalksEvents": "Vorträge",
  "targetContact": "Kontakt",
  "targetImprint": "Impressum",
  "targetPrivacy": "Datenschutz",
  "targetOtherLanguage": "English",
  "targetOtherLanguageTitle": "Change language to English",
  "targetHrCv": "Lebenslauf, Projekte, Skills",
  "targetHrCvUrl": "cv-projekte-skills.html",
  "intro": "Ich bin Ingo Steinke, kreativer Frontend-Webentwickler mit über 20 Jahren Berufserfahrung. Ich entwickle (programmiere), teste und optimiere Websites, Web Apps und Online-Shops. Aktuelle Anforderungen wie BFSG, DSGVO, Ladezeit und ökologische Nachhaltigkeit werden verständlich erklärt und pragmatisch umgesetzt.",
  "spacedAnd": " und",
  "andA": "und",
  "commaEnglishOnly": "",
  "currentlyEcologicalIam": "Ich arbeite gerne für Kundinnen und Kunden mit ökologischem und ethischem Fokus. Ich bin",
  "memberOf": "Mitglied im",
  "workWithMeHeading": "Angebot",
  "workWithMe":"Du möchtest deine Website überarbeiten? Dein Team braucht Verstärkung durch einen Frontend-Entwickler mit Fullstack-Erfahrung?",
  "ctaContact": "Ruf mich an oder hinterlasse mir eine Nachricht!",
  "workWithMe2": "Gern können wir uns bei einem Kaffee in Berlin, telefonisch oder per Zoom unverbindlich über dein Projekt unterhalten.",
  "projectsHeading": "Projekte",
  "projects": "Überzeuge dich selbst von meiner Arbeit!",
  "projectsMore1": "Auf der",
  "projectsMoreLinkText": "Seite über mich findest du weitere Projekte",
  "projectsHereAreSome": "Eine Auswahl meiner Projekte",
  "projectsScreenshots": "Screenshots",
  "projectWebsite": "Website",
  "projectSourceCode": "Quellcode",
  /* work */
  "workHeading": "Langlebig, barrierefrei und umweltfreundlich",
  "work": "Deine Layouts realisiere ich möglichst plattformübergreifend, responsiv und barrierefrei (BFSG-konform). Wir finden langlebige Lösungen, elegant, verständlich und pflegeleicht. Mehr dazu: <a href='/webseiten-klimafreundlich-barrierefrei-optimieren/'>Webseiten klimafreundlich und barrierefrei optimieren lassen</a>.",
  "workReliableHeading": "Zuverlässig und verständlich",
  "workReliable": "Mir ist es wichtig, technische Themen einfach zu erklären, die Wünsche meiner Kundschaft zu verstehen, weiterzudenken und nachhaltig umzusetzen.",
  "workClientsBenefit": "Als Kund:in profitierst du von geringeren Wartungskosten, optimierter Performance und erfolgreicher Kundenansprache.",
  "pricingHeading": "Preise",
  "workFullstack": "Bei der Weiterentwicklung bestehenden Codes kommt mir meine Berufserfahrung und meine pragmatische Einstellung zugute. Mit meinen Erfahrungen im Backend- und DevOps-Bereich und meiner hohen Lernbereitschaft übernehme ich bei Bedarf alle Aufgaben, die sich bei der Webentwicklung ergeben oder finde geeignete Partner:innen für die Umsetzung.",
  "pricing": "Ich biete verschiedene Preismodelle an. Bei einer Abrechnung auf Stundenbasis gebe ich üblicherweise im Vorfeld eine Aufwandsschätzung ab. Festpreisangebote sind ebenfalls möglich. Erfrage gerne ein individuelles Angebot!",
  "workOwnFocus": "Mein Schwerpunkt ist die Frontend-Entwicklung mit CSS.",
  "workCertifiedHeading": "Zertifiziert und transparent",
  "workCertifiedIam": "Ich bin",
  "workCertifiedSWDev": "zertifizierter Shopware 6 Developer",
  "projectShopwareCostPluginLinkUrl": "https://store.shopware.com/en/ingos57544164693f/cost-transparency.html",
  "workCertifiedSWDevPartnerPageUrl": "https://store.shopware.com/ingo-steinke.html",
  "workCertifiedPdfUrl": "Shopware-6-Certified-Developer-Ingo-Steinke-de.pdf",
  "workCertifiedAnd": "und",
  "workCertifiedExtensionPartner": "Shopware Extension Partner",
  "workCertifiedSustainableSourceCodeLinkText": "Der Quellcode meiner Arbeit",
  "workCertifiedSustainable2": "ist offen einsehbar, sofern es der Datenschutz erlaubt. Der ",
  "workCertifiedSustainableFootprintLinkText": "„CO<sub>2</sub>-Fußabdruck“ meiner Website",
  "workCertifiedSustainable3": "ist ebenfalls sichtbar ausgewiesen.",
  "workTeamHeading": "Teamwork und Netzwerk",
  "workTeam": "Ich habe kein festes Team, aber ein Netzwerk guter Geschäftsfreund:innen mit denen ich teilweise schon seit vielen Jahren zusammenarbeite. Als Kund:in kannst du mir aber auch gerne die Dienstleister:innen deines Vertrauens vorstellen. So behältst du selbst die volle Kontrolle und sparst dir Mehraufwand und wechselnde Ansprechpartner:innen klassischer Agenturen.",
  "workPluginsHeading": "Open Source / Plugin-Programmierung",
  "workPlugins1": "Schnittstellen zum Backend implementiere ich vorzugsweise als unabhängige Open-Source-Module.",
  "workPlugins5": "Aktuell arbeite ich an WordPress-Plugins zur",
  "workPlugins6": "vorzeitigen Erkennung von Plugin-Konflikten",
  "workPluginsAnd": "und",
  "workPlugins7": "zum Spam-Bericht für WordPress-Kontaktformulare",
  "workPluginsOther": "Zudem entwickelte ich Erweiterungen und Themes für Shopware, WebStorm und IntelliJ IDEA, unter anderem das kostenlos erhätliche",
  /* Skills */
  "SkillsHeading": "Fachkenntnisse (Skills)",
  "SkillsWebdevHeading": "Webentwicklung",
  "SkillsWebdevDb": "Datenbanken",
  "SkillsLib": "Software Stacks",
  "SkillsLibStaticSiteGenerators": "SSG",
  "SkillsLibDesignSystems": "Design-Systeme",
  "SkillsOther": "Sonstige Tools",
  "SkillsOtherQa": "Qualitätssicherung",
  "SkillsOtherVcs": "Codeverwaltung",
  "SkillsOtherDevops": "DevOps",
  "SkillsDevuxImg": "Kollaboration",
  "SkillsOtherSystems": "Sonstige Systeme und Software",
  /* About me, talks, and events */
  "aboutMeHeading": "Über mich: Webentwickler mit Begeisterung für UX-Design",
  "aboutMeIntroHeading": "Was mich immer noch fasziniert",
  "aboutMeIntro": "Weltweite Kommunikation und Inspiration: das World Wide Web verbindet die Menschen mithilfe robuster und dezentraler Technologie. Schöne, schnelle und barrierefreie Websites sollen allen Menschen Zugang zu diesem Netzwerk bieten. Diese Vision prägt meine Arbeit.",
  "aboutMeCvHeading": "Werdegang",
  "aboutMeCv1": "Interaktive Websites und Browserspiele waren die ersten Produkte meines 2000 mitgegründeten Startups in Münster. Suchmaschinenoptimierung und unsere eigene CMS- und Shop-Software bildeten später das Kerngeschäft.",
  "aboutMeCv2": "Als angestellter E-Commerce-Engineer bei Xsite in Düsseldorf entwickelte ich von 2010 bis 2014 Online-Shops für Shop-Apotheke.com, den Kunstversand Ars mundi und andere Kunden. Als Technical Consultant bei Sevenval Technologies (später Avenga Germany) in Köln und Berlin optimierte ich die Ladezeit und Handytauglichkeit von Apps und Websites der Frankfurter Allgemeinen Zeitung und Online-Shops der Otto Group und erstellte Frontend-Anwendungen für wao.io und andere Kunden. Seit Ende 2020 bin ich als selbstständiger Webentwickler und Freelancer für Agenturen und individuelle Kundinnen und Kunden tätig.",
  "aboutMeEthicalHeading": "Zukunftsthemen und nachhaltige Digitalisierung",
  "aboutMeEthical": "Digitalisierung steht in erster Linie für technologischen Fortschritt. Der wirtschaftliche Nutzen nachhaltiger Innovation wurde bisher oft übersehen. Ethische und ökologische Projekte beispielsweise in der Verkehrswende, bei erneuerbaren Energien und umweltfreundlicher Mode möchte ich mit meiner Arbeit unterstützen. Gesetzlichen Vorgaben wie der Datenschutz-Grundverordnung oder dem Barrierefreiheits-Stärkungs-Gesetz können wir dank meiner Erfahrung auf elegante Weise entsprechen.",
  "aboutMeEthicalImA": "Ich bin ein",
  "aboutMeEthicalA": "ein",
  "aboutMeEthicalandASignatory": " und unterzeichnete das",
  "aboutMeAtDev": "In meinem",
  "aboutMeDevBlog": "DEV Blog",
  "aboutMeAndOn": "und auf",
  "aboutMeOMCLinkText": "Open-Mind-Culture.org",
  "aboutMeIRegularly": "veröffentliche ich regelmäßig Artikel über Webentwicklung und damit zusammenhängende technologische und gesellschaftliche Themen.",
  "talksHeading": "Vorträge, Veranstaltungen, Kund:innenstimmen",
  "talksImageAlt": "Foto: Ingo Steinke, Frontend Web Developer, Freelancer, auf never code alone TV in 2021: Wenn ich denke, ich weiß immer besser, dann kommt jemand anders und sagt: Hey das kannst...",
  "talksImageCaption": "Bild",
  "talksImageLinkText": "Never Code Alone Conference 2021",
  "talks": "Konferenzen, Kurse und Meetups bieten gelegenheit zu fachlichem und persönlichem Austausch.",
  "talks2": "In den letzten Jahren hielt ich unter anderem diese Vorträge:",
  "talkMeetupWebVitals": "Core Web Vitals: Web Performance and Usability",
  "talkMeetupWebVitals2": "",
  "talkPerformanceNoCode": "Performance-Optimierung ohne Code-Änderung",
  "talkPerformanceNoCode2": "",
  "talkHsts": "HSTS: Mehr Sicherheit ohne Performanceverlust",
  "talkHsts2": "",
  "talkInfrastructure": "Infrastruktur für bessere Web Performance",
  "talkInfrastructure2": "",
  "memberships": "Mitgliedschaften",
  "testimonials": "Was meine Kund:innen sagen:",
  "testimonialsReadMoreText1": "Weitere Bewertungen bei Google lesen",
  "testimonialsReadMoreTitle1": "Google-Unternehmensprofil von Ingo Steinke",
  "testimonialsReadMoreLinkUrl1": "https://www.google.com/maps/place/Ingo+Steinke/@54.5871961,-51.7559002,3z/data=!4m13!1m3!11m2!2s1A_qFX3OC2-87_jFnYtJquSLGNds!3e1!3m8!1s0x47b8cf81dc94e4ab:0x756104e1aec1a165!8m2!3d52.4789132!4d13.4417945!9m1!1b1!15sCgEqWgMiASqSARB3ZWJzaXRlX2Rlc2lnbmVy4AEA!16s%2Fg%2F11qsm5r_br",
  "testimonialsReadMoreLinkUrl2": "https://www.provenexpert.com/ingo-steinke-creative-web-developer/",
  "testimonialDanielaQuote": "Ich hatte das Vergnügen mit Ingo zusammenzuarbeiten und bin begeistert von seiner Kompetenz im Bereich Webentwicklung. Er ist nicht nur technisch versiert, sondern auch konzeptionell stark. Besonders eindrucksvoll finde ich, dass Ingo für jedes Problem eine Lösung erarbeiten kann. Nicht zuletzt zeichnet er sich durch sein starkes Engagement im Bereich Nachhaltigkeit aus.",
  "testimonialDanielaAuthor": "Daniela, Designerin",
  "testimonialMalteQuote": "An meiner Seite haben bereits einige Programmierer und ITler gewerkelt, aber erst jetzt merke ich was für einen krassen Unterschied es machen kann.",
  "testimonialMalteAuthor": "Malte, Fotograf",
  "testimonialPatriciaQuote": "Wir sind total zufrieden mit Ingo. Absolut zuverlässig und tolle Ergebnisse. 100% Empfehlung!",
  "testimonialPatriciaAuthor": "Patricia, Coach",
  "testimonialsFiveStarRating": "Fünf-Sterne-Bewertung",
  /* Interested CTA */
  "interestedHeading": "Interessiert?",
  "interested": "Melde dich gerne, um ein unverbindliches Gespräch zu vereinbaren! Anfragen werden zeitnah beantwortet! Ich bin telefonisch, per E-Mail, per Signal oder WhatsApp erreichbar. Falls ich einen Anruf nicht annehmen kann, hinterlasse mir gerne eine Sprachnachricht!",
  /* Imprint, Contact */
  "imprintHeader": "Impressum und Kontaktdaten",
  "imprintName": "Ingo Steinke",
  "imprintRole": "Webentwickler",
  "imprintStreetAddress": "Donaustr. 83 II",
  "imprintPostalCode": "12043",
  "imprintCity": "Berlin",
  "imprintCountryName": "Deutschland",
  "postalAddressLabel": "Postanschrift",
  "untilDec22": "bis 31.12.2022",
  "contactTel": "+491634684080",
  "contactTelChunks": [
    "+49",
    "163",
    "46",
    "84",
    "08",
    "0"
  ],
  "contactTelOfflineLabel": "Telefon zeitweise nicht erreichbar",
  "contactInterimLabel": "übergangsweise stattdessen",
  "contactEmail": "kontakt@ingo-steinke.de",
  "taxNo": "Steuernr.",
  "vatIdLabel": "UStID",
  "vatIdNumber": "DE337676808",
  "insurance": "Berufshaftpflichtversicherung: Media-Haftpflicht",
  "insurancePrint1": "Berufshaftpflichtversicherung:",
  "insurancePrint2": "Exali Media-Haftfplicht",
  "insuranceTitle": "Berufshaftpflichtversicherung: exali Media-Haftpflicht",
  "bankaccountLabel": "Bankverbindung: GLS Gemeinschaftsbank eG",
  "bankaccountNumberChunks": [
    "DE89",
    "4306",
    "0967",
    "3029",
    "8400",
    "00"
  ],
  "contactOr": "oder",
  "scheduleAMeeting": "buche einen Termin über cal.com",
  "contactScheduleTitle": "Kontakt",
  "contactFormTitle": "Schreib mir eine Nachricht:",
  "contactFormMessageSending": "Deine Nachricht wird gesendet...",
  "contactFormMessageSent": "Danke! Deine Nachricht wurde gesendet.",
  "contactFormMessageError": "Deine Nachricht konnte leider nicht gesendet werden.",
  "contactFormLabelName": "Name",
  "contactFormPlaceholderYourName": "Dein Name",
  "contactFormLabelEmail": "E-Mail",
  "contactFormLabelPhone": "Telefon",
  "contactFormLabelContact": "Kontakt",
  "contactFormLabelEmailOrPhone": "Telefon oder E-Mail",
  "contactFormLabelMessage": "Deine Nachricht",
  "contactFormLabelHomepage": "Homepage",
  "contactFormLabelCaptcha": "Sicherheitsfrage",
  "contactFormButtonSubmit": "Nachricht absenden",
  "contactFormButtonSubmitRetry": "Nachricht erneut absenden",
  "profile": "Profil",
  "at": "auf",
  "vcardQrTitle": "Ingo-Steinke als Kontakt speichern",
  "vcardQrImgAlt": "QR-Code: Kontakt zu Ingo-Steinke",
  "vcardQrImgFilename": "ingo-steinke-de-vcard-qr.svg",
  "scanAndSaveContact1": "Kontakt scannen",
  "scanAndSaveContact2": "und speichern",
  "privacyGdpr": "Die Regeln des Bundesdatenschutzgesetzes (BDSG) und der europäischen Datenschutzgrundverordnung (DSGVO) sind Anlass zu dieser Datenschutzerklärung. Das",
  "privacyGdprImprint": "Impressum",
  "privacyGdpr2": "nennt den verantworlichen Anbieter und deine Möglichkeiten zur Kontaktaufnahme.",
  "privacyYourRightsHeading": "Dein gutes Recht: Auskunft, Korrektur, Löschung, Widerruf",
  "privacyYourRights": "Du hast das Recht, eine Einwilligung in die Verarbeitung deiner Daten zu verweigern oder nachträglich zu widerrufen, sowie das Recht auf Auskunft hinsichtlich der über deine Person gespeicherten Daten und können eine Löschung dieser Daten oder eine Korrektur unzutreffender Daten verlangen. Ausgenommen von der Löschung sind gespeicherte Daten, die der gesetzlichen Aufbewahrungspflicht bzw. der steuerlichen Abgabenordnung oder einer anderweitig vorgeschriebenen Datenspeicherung zur Geschäftsabwicklung unterliegen.",
  "privacyPersonalDataHeading": "Umfang der Verarbeitung personenbezogener Daten",
  "privacyPersonalData": "Personenbezogene Daten meiner Nutzer verarbeite ich grundsätzlich nur soweit, wie dies zur Vertragserfüllung, zu konkreten vorvertraglichen Vereinbarungen, sowie zur Bereitstellung einer funktionsfähigen Website erforderlich ist. Die Verarbeitung personenbezogener Daten meiner Nutzer erfolgt nur nach Einwilligung der Nutzerin bzw. des Nutzers, außer in solchen Fällen, in denen eine vorherige Einholung einer Einwilligung aus tatsächlichen Gründen nicht möglich ist und die Verarbeitung der Daten durch gesetzliche Vorschriften ausdrücklich gestattet oder gefordert ist.",
  "privacyLawHeading": "Rechtsgrundlage für die Verarbeitung personenbezogener Daten",
  "privacyLaw": "Bei der Verarbeitung von personenbezogenen Daten, die zur Erfüllung eines Vertrages mit der betroffenen Person als Vertragspartei erforderlich ist, dient Art. 6 Abs. 1 Bst. b DSGVO als Rechtsgrundlage. Dies gilt auch für Verarbeitungsvorgänge, die zur Durchführung vorvertraglicher Maßnahmen erforderlich sind.",
  "privacyLaw2": "Soweit eine Verarbeitung personenbezogener Daten zur Erfüllung einer rechtlichen Verpflichtung erforderlich ist, dient Art. 6 Abs. 1 Bst. c DSGVO als Rechtsgrundlage.",
  "privacyMinimalHeading": "Datensparsamkeit und Datenminimierung",
  "privacyMinimal": "Personenbezogene Daten speichere ich gemäß den Grundsätzen der Datenvermeidung und Datensparsamkeit nur so lange, wie es erforderlich ist oder vom Gesetzgeber her vorgeschrieben wird (gesetzliche Speicherfrist). Entfällt der Zweck der erhobenen Informationen oder endet die Speicherfrist, veranlasse ich die Sperrung bzw. Löschung der Daten.",
  "privacyNoCookies": "Diese Website verwendet keine Cookies. Auf dieser Website verzichte ich zudem auf Auswertungs- und Werbefunktionen externer Anbieter. Daher werden auch keinerlei Daten mit Google Analytics, Facebook oder ähnlichen Drittanbietern ausgetauscht.",
  "privacyLinkDisclaimer": "Verweise zu sozialen und beruflichen Netzwerken sind lediglich Links zu externen Anbietern. Anzeigen und Ansehen der dieser Verweise führt zu keiner Datenübertragung an Drittanbieter.",
  "privacyLogfilesHeading": "Bereitstellung der Website und Auswertung technischer Daten (Logfiles)",
  "privacyLogfiles": "Mit jedem Zugriff auf dieses Angebot werden durch mich beziehungsweise die von mir beauftragten Web-Provider und deren Dienstleister automatisch Informationen erfasst, die zur technischen Bereitstellung der Website erforderlich sind. Erfasst werden die Adresse der besuchten Website, Datum und Uhrzeit, übertragene Datenmenge, Webbrowserkennung, IP-Adresse und gegebenenfalls auf die aufgerufene Website verweisende Websites. Die Daten werden in den Logfiles der EDV gespeichert. Eine Speicherung dieser Daten zusammen mit anderen personenbezogenen Daten der Nutzer findet nicht statt. Eine Auswertung der Daten zu Marketingzwecken findet in diesem Zusammenhang ebenfalls nicht statt.",
  "privacyLogfilesLaw": "Rechtsgrundlage für die vorübergehende Speicherung dieser Daten und der Logfiles ist Art. 6 Abs. 1 Bst. f DSGVO. Die Speicherung in Logfiles erfolgt, um die Funktionsfähigkeit der Website sicherzustellen. Zudem dienen diese Daten zur Gewährleistung der Sicherheit der informationstechnischen Systeme. Ich behalte mir das Recht vor, die Server-Logfiles bei Verdacht auf eine rechtswidrige Nutzung meines Angebotes nachträglich zu kontrollieren.",
  "privacyChangesHeading": "Änderung dieser Datenschutzerklärung",
  "privacyChanges": "Um zu gewährleisten, dass diese Datenschutzerklärung stets den aktuellen gesetzlichen Vorgaben entspricht, behalte ich mir jederzeit Änderungen vor. Das gilt auch für den Fall, dass die Datenschutzerklärung aufgrund neuer oder überarbeiteter Leistungen, zum Beispiel neuer Serviceleistungen, angepasst werden muss. Die neue Datenschutzerklärung greift dann bei deinem nächsten Besuch auf meinem Angebot.",
  "ecofriendlyGreenWebCheckUrl": "https://www.thegreenwebfoundation.org/green-web-check/?url=https%3A%2F%2Fwww.ingo-steinke.de%2F",
  "ecofriendlyGreenWebCheckImageFilename": "badge-greencheckimage-www.ingo-steinke.de-2023",
  "ecofriendlyGreenWebCheckImageOriginalSrc": "https://api.thegreenwebfoundation.org/greencheckimage/www.ingo-steinke.de?nocache=true",
  "ecofriendlyGreenWebCheckImageAlt": "This website is hosted Green by goneo Internet GmbH - checked by thegreenwebfoundation.org",
  "ecofriendlyEcograderUrl": "https://ecograder.com/report/5bYzVEYfIxBO2JuMepQtSfBK",
  "ecofriendlyEcograderTitle": "Im November 2025 wurde diese Website besser als 89% aller mit Eocgrader getesteten URLs bewertet.",
  "ecofriendlyEcograderScore": "Ecograder Score: 93/100 (0.25 g CO₂e)",
  "listedAt": "Verzeichnet bei",
  "buttonStopAnimation": "Animation ausblenden",
  "buttonStartAnimation": "Animation einblenden",
  "buttonToggleAnimation": "Animation an/aus",
  "updatedWithColon": "aktualisiert am",
  "dotIfGerman": ".",
  "toggleHighContrast": "Kontrast ändern",
  "reduceContrast": "Kontrast verringern",
  "increaseContrast": "Kontrast erhöhen",
  "services": "Leistungen",
  "servicesBuildTitle": "Wir bauen deine Website!",
  "servicesBuildTitleAlternative": "Website-Erstellung",
  "servicesBuild1": "schnell erste Erfolge erreichen",
  "servicesBuild2": "nachhaltiges Konzept von Anfang an",
  "servicesBuild3": "langfristige Zusammenarbeit",
  "servicesBuild4": "Kooperation mit erfahrenen Partner:innen",
  "servicesBuildMoreLinkText": "jetzt starten",
  "servicesBuildMoreLinkTitle": "Professionelle Websiteerstellung",
  "servicesBuildMoreSubFooterLinkTitle": "Neue Website erstellen/entwickeln",
  "servicesBuildMoreSubFooterLinkText": "Erstellung",
  "servicesBuildMoreLinkPath": "leistungen/webentwicklung.html",
  "servicesVerifyTitle": "Wir testen deine Website!",
  "servicesVerifyTitleAlternative": "Website-Überprüfung",
  "servicesVerify1": "dein digitaler CO<sub>2</sub>-Fußabdruck",
  "servicesVerify2": "deine Ladezeit und Barrierefreiheit",
  "servicesVerify3": "kritische Fehler und Probleme",
  "servicesVerify4": "testen und zertifieren lassen",
  "servicesVerifyMoreLinkText": "jetzt prüfen",
  "servicesVerifyMoreLinkTitle": "mehr über Test und Analyse",
  "servicesVerifyMoreSubFooterLinkTitle": "Website-Qualität überprüfen",
  "servicesVerifyMoreSubFooterLinkText": "Web-Check",
  "servicesVerifyMoreLinkPath": "leistungen/website-check.html",
  "servicesImproveTitle": "Wir optimieren deine Website!",
  "servicesImproveTitleAlternative": "Website-Optimierung",
  "servicesImprove1": "deine Kund:innen werden sie lieben",
  "servicesImprove2": "perfekt für Computer und Smartphone",
  "servicesImprove3": "einfach bei Ecosia und Google zu finden",
  "servicesImprove4": "ökologisch effizient und zertifiziert",
  "servicesImproveMoreLinkText": "jetzt optimieren",
  "servicesImproveMoreLinkTitle": "mehr über Optimierung und Zertifizierung",
  "servicesImproveMoreSubFooterLinkTitle": "bestehende Websites verbessern",
  "servicesImproveMoreSubFooterLinkText": "Optimierung",
  "servicesImproveMoreLinkPath": "leistungen/optimierung.html",
  "showLandingpageLinks": "true",
  "landingLinkTitleWordPress":"Wordpress-Website nachhaltig optimieren lassen",
  "landingLinkTextWordPress": "WordPress",
  "landingLinkUrlWordPress": "https://www.ingo-steinke.de/wordpress-website-nachhaltig-optimieren-lassen/",
  "landingLinkTitleShopware": "Zertifizierter Shopware 6 + Frontend Webentwickler",
  "landingLinkTextShopware": "Shopware",
  "landingLinkUrlShopware": "https://www.ingo-steinke.de/zertifizierter-shopware-6-frontend-webentwickler/",
  "landingLinkTitleSustainability": "Webseiten klimafreundlich und barrierefrei optimieren lassen",
  "landingLinkTextSustainability": "Nachhaltigkeit",
  "landingLinkUrlSustainability": "https://www.ingo-steinke.de/webseiten-klimafreundlich-barrierefrei-optimieren/",
  "landingLinkTitleFreelanceBerlin": "Freelance Webentwickler in Berlin",
  "landingLinkTextFreelanceBerlin": "Freelancer Berlin",
  "landingLinkUrlFreelanceBerlin": "https://www.ingo-steinke.de/leistungen/webentwickler-berlin-freelancer.html",
  "landingLinkTextSitemap": "Sitemap",
  "landingLinkUrlSitemap": "https://www.ingo-steinke.de/sitemap.html",
  "languagesSubtitle": "Sprachen",
  "furtherInformationSubheading": "Weitere Informationen",
  "projectImgAltDefault": "Projekt-Screenshot",
  "userSitemapClaimTitle": "Sitemap: alles auf einen Blick",
  "userSitemapDescription": "Auf dieser Sitemap sind alle Unterseiten zu Angeboten, Dienstleistungen und Referenzen des Berliner Webentwicklers Ingo Steinke auf einen Blick zusammengefasst."
};


